<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class CatalogUserErrorCode
{
    public const APP_CATALOG_PRICE_LIST_ASSIGNMENT = 'APP_CATALOG_PRICE_LIST_ASSIGNMENT';
    public const BLANK = 'BLANK';
    public const CANNOT_ADD_MORE_THAN_ONE_MARKET = 'CANNOT_ADD_MORE_THAN_ONE_MARKET';
    public const CANNOT_CREATE_APP_CATALOG = 'CANNOT_CREATE_APP_CATALOG';
    public const CANNOT_CREATE_MARKET_CATALOG = 'CANNOT_CREATE_MARKET_CATALOG';
    public const CANNOT_DELETE_APP_CATALOG = 'CANNOT_DELETE_APP_CATALOG';
    public const CANNOT_DELETE_MARKET_CATALOG = 'CANNOT_DELETE_MARKET_CATALOG';
    public const CANNOT_MODIFY_APP_CATALOG = 'CANNOT_MODIFY_APP_CATALOG';
    public const CANNOT_MODIFY_MARKET_CATALOG = 'CANNOT_MODIFY_MARKET_CATALOG';
    public const CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_PRICE_BREAKS = 'CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_PRICE_BREAKS';
    public const CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES = 'CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES';
    public const CATALOG_FAILED_TO_SAVE = 'CATALOG_FAILED_TO_SAVE';
    public const CATALOG_NOT_FOUND = 'CATALOG_NOT_FOUND';
    public const CATALOG_PRICE_LIST_ASSIGNMENT = 'CATALOG_PRICE_LIST_ASSIGNMENT';
    public const COMPANY_LOCATION_CATALOG_STATUS_PLAN = 'COMPANY_LOCATION_CATALOG_STATUS_PLAN';
    public const COMPANY_LOCATION_NOT_FOUND = 'COMPANY_LOCATION_NOT_FOUND';
    public const CONTEXT_ALREADY_ASSIGNED_TO_CATALOG = 'CONTEXT_ALREADY_ASSIGNED_TO_CATALOG';
    public const CONTEXT_CATALOG_LIMIT_REACHED = 'CONTEXT_CATALOG_LIMIT_REACHED';
    public const CONTEXT_DRIVER_MISMATCH = 'CONTEXT_DRIVER_MISMATCH';
    public const COUNTRY_PRICE_LIST_ASSIGNMENT = 'COUNTRY_PRICE_LIST_ASSIGNMENT';
    public const INVALID = 'INVALID';
    public const INVALID_CATALOG_CONTEXT_TYPE = 'INVALID_CATALOG_CONTEXT_TYPE';
    public const MARKET_AND_PRICE_LIST_CURRENCY_MISMATCH = 'MARKET_AND_PRICE_LIST_CURRENCY_MISMATCH';
    public const MARKET_CATALOG_STATUS = 'MARKET_CATALOG_STATUS';
    public const MARKET_NOT_FOUND = 'MARKET_NOT_FOUND';
    public const MARKET_TAKEN = 'MARKET_TAKEN';
    public const MUST_PROVIDE_EXACTLY_ONE_CONTEXT_TYPE = 'MUST_PROVIDE_EXACTLY_ONE_CONTEXT_TYPE';
    public const PRICE_LIST_FAILED_TO_SAVE = 'PRICE_LIST_FAILED_TO_SAVE';
    public const PRICE_LIST_LOCKED = 'PRICE_LIST_LOCKED';
    public const PRICE_LIST_NOT_ALLOWED_FOR_PRIMARY_MARKET = 'PRICE_LIST_NOT_ALLOWED_FOR_PRIMARY_MARKET';
    public const PRICE_LIST_NOT_FOUND = 'PRICE_LIST_NOT_FOUND';
    public const PUBLICATION_NOT_FOUND = 'PUBLICATION_NOT_FOUND';
    public const REQUIRES_CONTEXTS_TO_ADD_OR_REMOVE = 'REQUIRES_CONTEXTS_TO_ADD_OR_REMOVE';
    public const TAKEN = 'TAKEN';
    public const TOO_LONG = 'TOO_LONG';
    public const TOO_SHORT = 'TOO_SHORT';
    public const UNSUPPORTED_CATALOG_ACTION = 'UNSUPPORTED_CATALOG_ACTION';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
