<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class CombinedListingUpdateUserErrorCode
{
    public const CANNOT_HAVE_DUPLICATED_PRODUCTS = 'CANNOT_HAVE_DUPLICATED_PRODUCTS';
    public const CANNOT_HAVE_PARENT_AS_CHILD = 'CANNOT_HAVE_PARENT_AS_CHILD';
    public const CANNOT_HAVE_REPEATED_OPTIONS = 'CANNOT_HAVE_REPEATED_OPTIONS';
    public const CANNOT_HAVE_REPEATED_OPTION_VALUES = 'CANNOT_HAVE_REPEATED_OPTION_VALUES';
    public const CANT_ADD_OPTIONS_VALUES_IF_ALREADY_EXISTS = 'CANT_ADD_OPTIONS_VALUES_IF_ALREADY_EXISTS';
    public const COMBINED_LISTINGS_NOT_ENABLED = 'COMBINED_LISTINGS_NOT_ENABLED';
    public const EDIT_AND_REMOVE_ON_SAME_PRODUCTS = 'EDIT_AND_REMOVE_ON_SAME_PRODUCTS';
    public const FAILED_TO_ADD_PRODUCTS = 'FAILED_TO_ADD_PRODUCTS';
    public const FAILED_TO_REMOVE_PRODUCTS = 'FAILED_TO_REMOVE_PRODUCTS';
    public const FAILED_TO_UPDATE_PRODUCTS = 'FAILED_TO_UPDATE_PRODUCTS';
    public const MUST_HAVE_SELECTED_OPTION_VALUES = 'MUST_HAVE_SELECTED_OPTION_VALUES';
    public const OPTIONS_MUST_BE_EQUAL_TO_THE_OTHER_COMPONENTS = 'OPTIONS_MUST_BE_EQUAL_TO_THE_OTHER_COMPONENTS';
    public const OPTION_NAME_CANNOT_BE_BLANK = 'OPTION_NAME_CANNOT_BE_BLANK';
    public const OPTION_VALUES_CANNOT_BE_BLANK = 'OPTION_VALUES_CANNOT_BE_BLANK';
    public const OPTION_VALUES_CANNOT_BE_EMPTY = 'OPTION_VALUES_CANNOT_BE_EMPTY';
    public const PARENT_PRODUCT_MUST_BE_A_COMBINED_LISTING = 'PARENT_PRODUCT_MUST_BE_A_COMBINED_LISTING';
    public const PRODUCT_IS_ALREADY_A_CHILD = 'PRODUCT_IS_ALREADY_A_CHILD';
    public const PRODUCT_MEMBERSHIP_NOT_FOUND = 'PRODUCT_MEMBERSHIP_NOT_FOUND';
    public const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
    public const TITLE_TOO_LONG = 'TITLE_TOO_LONG';
    public const TOO_MANY_VARIANTS = 'TOO_MANY_VARIANTS';
    public const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
