<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class EnvironmentVariablesUserErrorCode
{
    public const CANT_MODIFY_READ_ONLY_ENVIRONMENT_VARIABLE = 'CANT_MODIFY_READ_ONLY_ENVIRONMENT_VARIABLE';
    public const CANT_REVEAL_SECRET_VARIABLES = 'CANT_REVEAL_SECRET_VARIABLES';
    public const DUPLICATE_ENVIRONMENT_VARIABLE_KEY_FOR_ENVIRONMENT = 'DUPLICATE_ENVIRONMENT_VARIABLE_KEY_FOR_ENVIRONMENT';
    public const DUPLICATE_ENVIRONMENT_VARIABLE_KEY_ON_CREATE = 'DUPLICATE_ENVIRONMENT_VARIABLE_KEY_ON_CREATE';
    public const DUPLICATE_ENVIRONMENT_VARIABLE_KEY_VALUE = 'DUPLICATE_ENVIRONMENT_VARIABLE_KEY_VALUE';
    public const ENVIRONMENTS_NOT_FOUND = 'ENVIRONMENTS_NOT_FOUND';
    public const ENVIRONMENT_NOT_FOUND = 'ENVIRONMENT_NOT_FOUND';
    public const MAXIMUM_ENVIRONMENT_VARIABLES_PER_ENVIRONMENT = 'MAXIMUM_ENVIRONMENT_VARIABLES_PER_ENVIRONMENT';
    public const STOREFRONT_DISCONNECTED = 'STOREFRONT_DISCONNECTED';
    public const STOREFRONT_NOT_FOUND = 'STOREFRONT_NOT_FOUND';
    public const UNASSIGNED_ENVIRONMENT_VARIABLE_VALUE = 'UNASSIGNED_ENVIRONMENT_VARIABLE_VALUE';
    public const USER_INPUT_MUST_UPDATE_VARIABLES_WITH_THE_SAME_KEY = 'USER_INPUT_MUST_UPDATE_VARIABLES_WITH_THE_SAME_KEY';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
