<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class FileErrorCode
{
    public const DUPLICATE_FILENAME_ERROR = 'DUPLICATE_FILENAME_ERROR';
    public const EXTERNAL_VIDEO_EMBED_DISABLED = 'EXTERNAL_VIDEO_EMBED_DISABLED';
    public const EXTERNAL_VIDEO_EMBED_NOT_FOUND_OR_TRANSCODING = 'EXTERNAL_VIDEO_EMBED_NOT_FOUND_OR_TRANSCODING';
    public const EXTERNAL_VIDEO_INVALID_ASPECT_RATIO = 'EXTERNAL_VIDEO_INVALID_ASPECT_RATIO';
    public const EXTERNAL_VIDEO_NOT_FOUND = 'EXTERNAL_VIDEO_NOT_FOUND';
    public const EXTERNAL_VIDEO_UNLISTED = 'EXTERNAL_VIDEO_UNLISTED';
    public const FILE_STORAGE_LIMIT_EXCEEDED = 'FILE_STORAGE_LIMIT_EXCEEDED';
    public const GENERIC_FILE_DOWNLOAD_FAILURE = 'GENERIC_FILE_DOWNLOAD_FAILURE';
    public const GENERIC_FILE_INVALID_SIZE = 'GENERIC_FILE_INVALID_SIZE';
    public const IMAGE_DOWNLOAD_FAILURE = 'IMAGE_DOWNLOAD_FAILURE';
    public const IMAGE_PROCESSING_FAILURE = 'IMAGE_PROCESSING_FAILURE';
    public const INVALID_IMAGE_ASPECT_RATIO = 'INVALID_IMAGE_ASPECT_RATIO';
    public const INVALID_IMAGE_FILE_SIZE = 'INVALID_IMAGE_FILE_SIZE';
    public const INVALID_IMAGE_RESOLUTION = 'INVALID_IMAGE_RESOLUTION';
    public const INVALID_SIGNED_URL = 'INVALID_SIGNED_URL';
    public const MEDIA_TIMEOUT_ERROR = 'MEDIA_TIMEOUT_ERROR';
    public const MODEL3D_GLB_OUTPUT_CREATION_ERROR = 'MODEL3D_GLB_OUTPUT_CREATION_ERROR';
    public const MODEL3D_GLB_TO_USDZ_CONVERSION_ERROR = 'MODEL3D_GLB_TO_USDZ_CONVERSION_ERROR';
    public const MODEL3D_PROCESSING_FAILURE = 'MODEL3D_PROCESSING_FAILURE';
    public const MODEL3D_THUMBNAIL_GENERATION_ERROR = 'MODEL3D_THUMBNAIL_GENERATION_ERROR';
    public const MODEL3D_THUMBNAIL_REGENERATION_ERROR = 'MODEL3D_THUMBNAIL_REGENERATION_ERROR';
    public const MODEL3D_VALIDATION_ERROR = 'MODEL3D_VALIDATION_ERROR';
    public const REVERT_MEDIA_VERSION_FAILURE = 'REVERT_MEDIA_VERSION_FAILURE';
    public const UNKNOWN = 'UNKNOWN';
    public const UNSUPPORTED_IMAGE_FILE_TYPE = 'UNSUPPORTED_IMAGE_FILE_TYPE';
    public const VIDEO_INVALID_FILETYPE_ERROR = 'VIDEO_INVALID_FILETYPE_ERROR';
    public const VIDEO_MAX_DURATION_ERROR = 'VIDEO_MAX_DURATION_ERROR';
    public const VIDEO_MAX_HEIGHT_ERROR = 'VIDEO_MAX_HEIGHT_ERROR';
    public const VIDEO_MAX_WIDTH_ERROR = 'VIDEO_MAX_WIDTH_ERROR';
    public const VIDEO_METADATA_READ_ERROR = 'VIDEO_METADATA_READ_ERROR';
    public const VIDEO_MIN_DURATION_ERROR = 'VIDEO_MIN_DURATION_ERROR';
    public const VIDEO_MIN_HEIGHT_ERROR = 'VIDEO_MIN_HEIGHT_ERROR';
    public const VIDEO_MIN_WIDTH_ERROR = 'VIDEO_MIN_WIDTH_ERROR';
    public const VIDEO_VALIDATION_ERROR = 'VIDEO_VALIDATION_ERROR';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
