<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class LanguageCode
{
    public const AF = 'AF';
    public const AK = 'AK';
    public const AM = 'AM';
    public const AR = 'AR';
    public const AS = 'AS';
    public const AZ = 'AZ';
    public const BE = 'BE';
    public const BG = 'BG';
    public const BM = 'BM';
    public const BN = 'BN';
    public const BO = 'BO';
    public const BR = 'BR';
    public const BS = 'BS';
    public const CA = 'CA';
    public const CE = 'CE';
    public const CKB = 'CKB';
    public const CS = 'CS';
    public const CU = 'CU';
    public const CY = 'CY';
    public const DA = 'DA';
    public const DE = 'DE';
    public const DZ = 'DZ';
    public const EE = 'EE';
    public const EL = 'EL';
    public const EN = 'EN';
    public const EO = 'EO';
    public const ES = 'ES';
    public const ET = 'ET';
    public const EU = 'EU';
    public const FA = 'FA';
    public const FF = 'FF';
    public const FI = 'FI';
    public const FIL = 'FIL';
    public const FO = 'FO';
    public const FR = 'FR';
    public const FY = 'FY';
    public const GA = 'GA';
    public const GD = 'GD';
    public const GL = 'GL';
    public const GU = 'GU';
    public const GV = 'GV';
    public const HA = 'HA';
    public const HE = 'HE';
    public const HI = 'HI';
    public const HR = 'HR';
    public const HU = 'HU';
    public const HY = 'HY';
    public const IA = 'IA';
    public const ID = 'ID';
    public const IG = 'IG';
    public const II = 'II';
    public const IS = 'IS';
    public const IT = 'IT';
    public const JA = 'JA';
    public const JV = 'JV';
    public const KA = 'KA';
    public const KI = 'KI';
    public const KK = 'KK';
    public const KL = 'KL';
    public const KM = 'KM';
    public const KN = 'KN';
    public const KO = 'KO';
    public const KS = 'KS';
    public const KU = 'KU';
    public const KW = 'KW';
    public const KY = 'KY';
    public const LB = 'LB';
    public const LG = 'LG';
    public const LN = 'LN';
    public const LO = 'LO';
    public const LT = 'LT';
    public const LU = 'LU';
    public const LV = 'LV';
    public const MG = 'MG';
    public const MI = 'MI';
    public const MK = 'MK';
    public const ML = 'ML';
    public const MN = 'MN';
    public const MR = 'MR';
    public const MS = 'MS';
    public const MT = 'MT';
    public const MY = 'MY';
    public const NB = 'NB';
    public const ND = 'ND';
    public const NE = 'NE';
    public const NL = 'NL';
    public const NN = 'NN';
    public const NO = 'NO';
    public const OM = 'OM';
    public const OR = 'OR';
    public const OS = 'OS';
    public const PA = 'PA';
    public const PL = 'PL';
    public const PS = 'PS';
    public const PT = 'PT';
    public const PT_BR = 'PT_BR';
    public const PT_PT = 'PT_PT';
    public const QU = 'QU';
    public const RM = 'RM';
    public const RN = 'RN';
    public const RO = 'RO';
    public const RU = 'RU';
    public const RW = 'RW';
    public const SA = 'SA';
    public const SC = 'SC';
    public const SD = 'SD';
    public const SE = 'SE';
    public const SG = 'SG';
    public const SI = 'SI';
    public const SK = 'SK';
    public const SL = 'SL';
    public const SN = 'SN';
    public const SO = 'SO';
    public const SQ = 'SQ';
    public const SR = 'SR';
    public const SU = 'SU';
    public const SV = 'SV';
    public const SW = 'SW';
    public const TA = 'TA';
    public const TE = 'TE';
    public const TG = 'TG';
    public const TH = 'TH';
    public const TI = 'TI';
    public const TK = 'TK';
    public const TO = 'TO';
    public const TR = 'TR';
    public const TT = 'TT';
    public const UG = 'UG';
    public const UK = 'UK';
    public const UR = 'UR';
    public const UZ = 'UZ';
    public const VI = 'VI';
    public const VO = 'VO';
    public const WO = 'WO';
    public const XH = 'XH';
    public const YI = 'YI';
    public const YO = 'YO';
    public const ZH = 'ZH';
    public const ZH_CN = 'ZH_CN';
    public const ZH_TW = 'ZH_TW';
    public const ZU = 'ZU';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
