<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class LocationDeactivateUserErrorCode
{
    public const CANNOT_DISABLE_ONLINE_ORDER_FULFILLMENT = 'CANNOT_DISABLE_ONLINE_ORDER_FULFILLMENT';
    public const DESTINATION_LOCATION_IS_THE_SAME_LOCATION = 'DESTINATION_LOCATION_IS_THE_SAME_LOCATION';
    public const DESTINATION_LOCATION_NOT_FOUND_OR_INACTIVE = 'DESTINATION_LOCATION_NOT_FOUND_OR_INACTIVE';
    public const FAILED_TO_RELOCATE_ACTIVE_INVENTORIES = 'FAILED_TO_RELOCATE_ACTIVE_INVENTORIES';
    public const FAILED_TO_RELOCATE_INCOMING_MOVEMENTS = 'FAILED_TO_RELOCATE_INCOMING_MOVEMENTS';
    public const FAILED_TO_RELOCATE_OPEN_PURCHASE_ORDERS = 'FAILED_TO_RELOCATE_OPEN_PURCHASE_ORDERS';
    public const FAILED_TO_RELOCATE_OPEN_TRANSFERS = 'FAILED_TO_RELOCATE_OPEN_TRANSFERS';
    public const HAS_ACTIVE_INVENTORY_ERROR = 'HAS_ACTIVE_INVENTORY_ERROR';
    public const HAS_ACTIVE_RETAIL_SUBSCRIPTIONS = 'HAS_ACTIVE_RETAIL_SUBSCRIPTIONS';
    public const HAS_FULFILLMENT_ORDERS_ERROR = 'HAS_FULFILLMENT_ORDERS_ERROR';
    public const HAS_INCOMING_MOVEMENTS_ERROR = 'HAS_INCOMING_MOVEMENTS_ERROR';
    public const HAS_OPEN_PURCHASE_ORDERS_ERROR = 'HAS_OPEN_PURCHASE_ORDERS_ERROR';
    public const HAS_OPEN_TRANSFERS_ERROR = 'HAS_OPEN_TRANSFERS_ERROR';
    public const LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND';
    public const PERMANENTLY_BLOCKED_FROM_DEACTIVATION_ERROR = 'PERMANENTLY_BLOCKED_FROM_DEACTIVATION_ERROR';
    public const TEMPORARILY_BLOCKED_FROM_DEACTIVATION_ERROR = 'TEMPORARILY_BLOCKED_FROM_DEACTIVATION_ERROR';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
