<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class MarketUserErrorCode
{
    public const BLANK = 'BLANK';
    public const CANNOT_ADD_CUSTOMER_DOMAIN = 'CANNOT_ADD_CUSTOMER_DOMAIN';
    public const CANNOT_ADD_REGIONS_TO_PRIMARY_MARKET = 'CANNOT_ADD_REGIONS_TO_PRIMARY_MARKET';
    public const CANNOT_ADD_WEB_PRESENCE_TO_PRIMARY_MARKET = 'CANNOT_ADD_WEB_PRESENCE_TO_PRIMARY_MARKET';
    public const CANNOT_DELETE_ONLY_REGION = 'CANNOT_DELETE_ONLY_REGION';
    public const CANNOT_DELETE_PRIMARY_MARKET = 'CANNOT_DELETE_PRIMARY_MARKET';
    public const CANNOT_DELETE_PRIMARY_MARKET_WEB_PRESENCE = 'CANNOT_DELETE_PRIMARY_MARKET_WEB_PRESENCE';
    public const CANNOT_DISABLE_PRIMARY_MARKET = 'CANNOT_DISABLE_PRIMARY_MARKET';
    public const CANNOT_HAVE_BOTH_SUBFOLDER_AND_DOMAIN_WEB_PRESENCES = 'CANNOT_HAVE_BOTH_SUBFOLDER_AND_DOMAIN_WEB_PRESENCES';
    public const CANNOT_HAVE_MULTIPLE_SUBFOLDERS_PER_MARKET = 'CANNOT_HAVE_MULTIPLE_SUBFOLDERS_PER_MARKET';
    public const CANNOT_HAVE_SUBFOLDER_AND_DOMAIN = 'CANNOT_HAVE_SUBFOLDER_AND_DOMAIN';
    public const CANNOT_SET_DEFAULT_LOCALE_TO_NULL = 'CANNOT_SET_DEFAULT_LOCALE_TO_NULL';
    public const DISABLED_LANGUAGE = 'DISABLED_LANGUAGE';
    public const DOMAIN_NOT_FOUND = 'DOMAIN_NOT_FOUND';
    public const DUPLICATE_LANGUAGES = 'DUPLICATE_LANGUAGES';
    public const INVALID = 'INVALID';
    public const MARKET_NOT_FOUND = 'MARKET_NOT_FOUND';
    public const MARKET_REACHED_WEB_PRESENCE_LIMIT = 'MARKET_REACHED_WEB_PRESENCE_LIMIT';
    public const NO_LANGUAGES = 'NO_LANGUAGES';
    public const PRIMARY_MARKET_MUST_USE_PRIMARY_DOMAIN = 'PRIMARY_MARKET_MUST_USE_PRIMARY_DOMAIN';
    public const REGION_NOT_FOUND = 'REGION_NOT_FOUND';
    public const REGION_SPECIFIC_LANGUAGE = 'REGION_SPECIFIC_LANGUAGE';
    public const REQUIRES_DOMAIN_OR_SUBFOLDER = 'REQUIRES_DOMAIN_OR_SUBFOLDER';
    public const REQUIRES_EXACTLY_ONE_OPTION = 'REQUIRES_EXACTLY_ONE_OPTION';
    public const SHOP_REACHED_MARKETS_LIMIT = 'SHOP_REACHED_MARKETS_LIMIT';
    public const SUBFOLDER_SUFFIX_CANNOT_BE_SCRIPT_CODE = 'SUBFOLDER_SUFFIX_CANNOT_BE_SCRIPT_CODE';
    public const SUBFOLDER_SUFFIX_MUST_CONTAIN_ONLY_LETTERS = 'SUBFOLDER_SUFFIX_MUST_CONTAIN_ONLY_LETTERS';
    public const TAKEN = 'TAKEN';
    public const TOO_LONG = 'TOO_LONG';
    public const TOO_SHORT = 'TOO_SHORT';
    public const UNPUBLISHED_LANGUAGE = 'UNPUBLISHED_LANGUAGE';
    public const UNSUPPORTED_COUNTRY_REGION = 'UNSUPPORTED_COUNTRY_REGION';
    public const WEB_PRESENCE_NOT_FOUND = 'WEB_PRESENCE_NOT_FOUND';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
