<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class MarketingActivityUserErrorCode
{
    public const ACTIVITY_NOT_EXTERNAL = 'ACTIVITY_NOT_EXTERNAL';
    public const CANNOT_DELETE_ACTIVITY_WITH_CHILD_EVENTS = 'CANNOT_DELETE_ACTIVITY_WITH_CHILD_EVENTS';
    public const CANNOT_UPDATE_TACTIC_IF_ORIGINALLY_STOREFRONT_APP = 'CANNOT_UPDATE_TACTIC_IF_ORIGINALLY_STOREFRONT_APP';
    public const CANNOT_UPDATE_TACTIC_TO_STOREFRONT_APP = 'CANNOT_UPDATE_TACTIC_TO_STOREFRONT_APP';
    public const CURRENCY_CODE_MISMATCH_INPUT = 'CURRENCY_CODE_MISMATCH_INPUT';
    public const DELETE_JOB_ENQUEUED = 'DELETE_JOB_ENQUEUED';
    public const DELETE_JOB_FAILED_TO_ENQUEUE = 'DELETE_JOB_FAILED_TO_ENQUEUE';
    public const IMMUTABLE_CHANNEL_HANDLE = 'IMMUTABLE_CHANNEL_HANDLE';
    public const IMMUTABLE_HIERARCHY_LEVEL = 'IMMUTABLE_HIERARCHY_LEVEL';
    public const IMMUTABLE_PARENT_ID = 'IMMUTABLE_PARENT_ID';
    public const IMMUTABLE_URL_PARAMETER = 'IMMUTABLE_URL_PARAMETER';
    public const IMMUTABLE_UTM_PARAMETERS = 'IMMUTABLE_UTM_PARAMETERS';
    public const INVALID = 'INVALID';
    public const INVALID_CHANNEL_HANDLE = 'INVALID_CHANNEL_HANDLE';
    public const INVALID_DELETE_ACTIVITY_EXTERNAL_ARGUMENTS = 'INVALID_DELETE_ACTIVITY_EXTERNAL_ARGUMENTS';
    public const INVALID_DELETE_ENGAGEMENTS_ARGUMENTS = 'INVALID_DELETE_ENGAGEMENTS_ARGUMENTS';
    public const INVALID_MARKETING_ACTIVITY_EXTERNAL_ARGUMENTS = 'INVALID_MARKETING_ACTIVITY_EXTERNAL_ARGUMENTS';
    public const INVALID_MARKETING_ENGAGEMENT_ARGUMENTS = 'INVALID_MARKETING_ENGAGEMENT_ARGUMENTS';
    public const INVALID_MARKETING_ENGAGEMENT_ARGUMENT_MISSING = 'INVALID_MARKETING_ENGAGEMENT_ARGUMENT_MISSING';
    public const INVALID_REMOTE_ID = 'INVALID_REMOTE_ID';
    public const MARKETING_ACTIVITY_CURRENCY_CODE_MISMATCH = 'MARKETING_ACTIVITY_CURRENCY_CODE_MISMATCH';
    public const MARKETING_ACTIVITY_DOES_NOT_EXIST = 'MARKETING_ACTIVITY_DOES_NOT_EXIST';
    public const MARKETING_EVENT_DOES_NOT_EXIST = 'MARKETING_EVENT_DOES_NOT_EXIST';
    public const NON_HIERARCHIAL_REQUIRES_UTM_URL_PARAMETER = 'NON_HIERARCHIAL_REQUIRES_UTM_URL_PARAMETER';
    public const TAKEN = 'TAKEN';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
