<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class ParseErrorCode
{
    public const BACKFILL_DATE_RANGE_NOT_FOUND = 'BACKFILL_DATE_RANGE_NOT_FOUND';
    public const COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND';
    public const COMPARE_TO_INCOMPATIBLE_PERIOD = 'COMPARE_TO_INCOMPATIBLE_PERIOD';
    public const COMPARE_TO_INVALID_PERIOD = 'COMPARE_TO_INVALID_PERIOD';
    public const COMPARE_TO_MISSING_PERIOD = 'COMPARE_TO_MISSING_PERIOD';
    public const COMPARISON_WITH_NON_AGGREGATE_FIELDS = 'COMPARISON_WITH_NON_AGGREGATE_FIELDS';
    public const DATE_INTERVAL_NOT_FOUND = 'DATE_INTERVAL_NOT_FOUND';
    public const DATE_NOT_PARSABLE = 'DATE_NOT_PARSABLE';
    public const DATE_TIME_NOT_PARSABLE = 'DATE_TIME_NOT_PARSABLE';
    public const EXCESS_BACKFILL_DIMENSIONS = 'EXCESS_BACKFILL_DIMENSIONS';
    public const EXCESS_DIMENSIONS = 'EXCESS_DIMENSIONS';
    public const EXCESS_PERIODS = 'EXCESS_PERIODS';
    public const EXCESS_PRESENTMENTS = 'EXCESS_PRESENTMENTS';
    public const FROM_NOT_FOUND = 'FROM_NOT_FOUND';
    public const FUNCTION_ARGUMENTS_NOT_FOUND = 'FUNCTION_ARGUMENTS_NOT_FOUND';
    public const FUNCTION_EXCESS_ARGUMENTS = 'FUNCTION_EXCESS_ARGUMENTS';
    public const FUNCTION_INCOMPATIBLE_TYPES = 'FUNCTION_INCOMPATIBLE_TYPES';
    public const FUNCTION_MODIFIER_NOT_FOUND = 'FUNCTION_MODIFIER_NOT_FOUND';
    public const FUNCTION_NESTED_AGGREGATE = 'FUNCTION_NESTED_AGGREGATE';
    public const FUNCTION_NOT_FOUND = 'FUNCTION_NOT_FOUND';
    public const INVALID_DATE_RANGE = 'INVALID_DATE_RANGE';
    public const LIMIT_INVALID = 'LIMIT_INVALID';
    public const LIST_MIXED_ARGUMENT_TYPES = 'LIST_MIXED_ARGUMENT_TYPES';
    public const MIXED_AGGREGATE_AND_NON_AGGREGATE = 'MIXED_AGGREGATE_AND_NON_AGGREGATE';
    public const NAMED_DATE_NOT_FOUND = 'NAMED_DATE_NOT_FOUND';
    public const OPERATOR_INCOMPATIBLE_TYPES = 'OPERATOR_INCOMPATIBLE_TYPES';
    public const PRESENTMENT_NOT_FOUND = 'PRESENTMENT_NOT_FOUND';
    public const REQUIRED_GROUP_BY_NOT_FOUND = 'REQUIRED_GROUP_BY_NOT_FOUND';
    public const SEMANTICALLY_INVALID = 'SEMANTICALLY_INVALID';
    public const SORT_FIELD_NOT_FOUND = 'SORT_FIELD_NOT_FOUND';
    public const SYNTAX_FAILED_PREDICATE = 'SYNTAX_FAILED_PREDICATE';
    public const SYNTAX_INPUT_MISMATCH = 'SYNTAX_INPUT_MISMATCH';
    public const SYNTAX_INVALID_TOKEN = 'SYNTAX_INVALID_TOKEN';
    public const SYNTAX_MISSING_TOKEN = 'SYNTAX_MISSING_TOKEN';
    public const SYNTAX_NOT_RECOGNIZED = 'SYNTAX_NOT_RECOGNIZED';
    public const SYNTAX_NO_VIABLE_ALTERNATIVE = 'SYNTAX_NO_VIABLE_ALTERNATIVE';
    public const SYNTAX_UNWANTED_TOKEN = 'SYNTAX_UNWANTED_TOKEN';
    public const TABLE_NOT_FOUND = 'TABLE_NOT_FOUND';
    public const TIME_FUNCTION_NOT_FOUND = 'TIME_FUNCTION_NOT_FOUND';
    public const UNBACKFILLED_TIME_GROUP_BY_COMPARISON = 'UNBACKFILLED_TIME_GROUP_BY_COMPARISON';
    public const UNKNOWN = 'UNKNOWN';
    public const VALUE_NOT_PARSABLE = 'VALUE_NOT_PARSABLE';
    public const VISUALIZE_CHART_TYPE_NOT_FOUND = 'VISUALIZE_CHART_TYPE_NOT_FOUND';
    public const VISUALIZE_EXCESS_PROJECTIONS = 'VISUALIZE_EXCESS_PROJECTIONS';
    public const VISUALIZE_GROUP_BY_MIXED_BACKFILL = 'VISUALIZE_GROUP_BY_MIXED_BACKFILL';
    public const VISUALIZE_GROUP_BY_NOT_FOUND = 'VISUALIZE_GROUP_BY_NOT_FOUND';
    public const VISUALIZE_INCOMPATIBLE_TYPES = 'VISUALIZE_INCOMPATIBLE_TYPES';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
