<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class PriceListUserErrorCode
{
    public const APP_CATALOG_PRICE_LIST_ASSIGNMENT = 'APP_CATALOG_PRICE_LIST_ASSIGNMENT';
    public const BLANK = 'BLANK';
    public const CATALOG_ASSIGNMENT_NOT_ALLOWED = 'CATALOG_ASSIGNMENT_NOT_ALLOWED';
    public const CATALOG_CANNOT_CHANGE_CONTEXT_TYPE = 'CATALOG_CANNOT_CHANGE_CONTEXT_TYPE';
    public const CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_PRICE_BREAKS = 'CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_PRICE_BREAKS';
    public const CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES = 'CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES';
    public const CATALOG_DOES_NOT_EXIST = 'CATALOG_DOES_NOT_EXIST';
    public const CATALOG_MARKET_AND_PRICE_LIST_CURRENCY_MISMATCH = 'CATALOG_MARKET_AND_PRICE_LIST_CURRENCY_MISMATCH';
    public const CATALOG_TAKEN = 'CATALOG_TAKEN';
    public const COMPANY_LOCATION_NOT_FOUND = 'COMPANY_LOCATION_NOT_FOUND';
    public const COMPANY_LOCATION_PRICE_LIST_LIMIT_REACHED = 'COMPANY_LOCATION_PRICE_LIST_LIMIT_REACHED';
    public const CONTEXT_RULE_COUNTRIES_LIMIT = 'CONTEXT_RULE_COUNTRIES_LIMIT';
    public const CONTEXT_RULE_COUNTRY_TAKEN = 'CONTEXT_RULE_COUNTRY_TAKEN';
    public const CONTEXT_RULE_LIMIT_ONE_OPTION = 'CONTEXT_RULE_LIMIT_ONE_OPTION';
    public const CONTEXT_RULE_LIMIT_REACHED = 'CONTEXT_RULE_LIMIT_REACHED';
    public const CONTEXT_RULE_MARKET_NOT_FOUND = 'CONTEXT_RULE_MARKET_NOT_FOUND';
    public const CONTEXT_RULE_MARKET_TAKEN = 'CONTEXT_RULE_MARKET_TAKEN';
    public const COUNTRY_CURRENCY_MISMATCH = 'COUNTRY_CURRENCY_MISMATCH';
    public const COUNTRY_PRICE_LIST_ASSIGNMENT = 'COUNTRY_PRICE_LIST_ASSIGNMENT';
    public const CURRENCY_COUNTRY_MISMATCH = 'CURRENCY_COUNTRY_MISMATCH';
    public const CURRENCY_MARKET_MISMATCH = 'CURRENCY_MARKET_MISMATCH';
    public const CURRENCY_NOT_SUPPORTED = 'CURRENCY_NOT_SUPPORTED';
    public const GENERIC_ERROR = 'GENERIC_ERROR';
    public const INCLUSION = 'INCLUSION';
    public const INVALID_ADJUSTMENT_MAX_VALUE = 'INVALID_ADJUSTMENT_MAX_VALUE';
    public const INVALID_ADJUSTMENT_MIN_VALUE = 'INVALID_ADJUSTMENT_MIN_VALUE';
    public const INVALID_ADJUSTMENT_VALUE = 'INVALID_ADJUSTMENT_VALUE';
    public const MARKET_CURRENCY_MISMATCH = 'MARKET_CURRENCY_MISMATCH';
    public const PRICE_LIST_LOCKED = 'PRICE_LIST_LOCKED';
    public const PRICE_LIST_NOT_ALLOWED_FOR_PRIMARY_MARKET = 'PRICE_LIST_NOT_ALLOWED_FOR_PRIMARY_MARKET';
    public const PRICE_LIST_NOT_FOUND = 'PRICE_LIST_NOT_FOUND';
    public const TAKEN = 'TAKEN';
    public const TOO_LONG = 'TOO_LONG';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
