<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class ProductVariantRelationshipBulkUpdateUserErrorCode
{
    public const CHILD_PRODUCT_VARIANT_CANNOT_BE_COMBINED_LISTING = 'CHILD_PRODUCT_VARIANT_CANNOT_BE_COMBINED_LISTING';
    public const CIRCULAR_REFERENCE = 'CIRCULAR_REFERENCE';
    public const DUPLICATE_PRODUCT_VARIANT_RELATIONSHIP = 'DUPLICATE_PRODUCT_VARIANT_RELATIONSHIP';
    public const EXCEEDED_PRODUCT_VARIANT_RELATIONSHIP_LIMIT = 'EXCEEDED_PRODUCT_VARIANT_RELATIONSHIP_LIMIT';
    public const FAILED_TO_CREATE = 'FAILED_TO_CREATE';
    public const FAILED_TO_REMOVE = 'FAILED_TO_REMOVE';
    public const FAILED_TO_UPDATE = 'FAILED_TO_UPDATE';
    public const FAILED_TO_UPDATE_PARENT_PRODUCT_VARIANT_PRICE = 'FAILED_TO_UPDATE_PARENT_PRODUCT_VARIANT_PRICE';
    public const INVALID_QUANTITY = 'INVALID_QUANTITY';
    public const MUST_SPECIFY_COMPONENTS = 'MUST_SPECIFY_COMPONENTS';
    public const NESTED_PARENT_PRODUCT_VARIANT = 'NESTED_PARENT_PRODUCT_VARIANT';
    public const PARENT_PRODUCT_VARIANT_CANNOT_BE_COMBINED_LISTING = 'PARENT_PRODUCT_VARIANT_CANNOT_BE_COMBINED_LISTING';
    public const PARENT_PRODUCT_VARIANT_CANNOT_BE_GIFT_CARD = 'PARENT_PRODUCT_VARIANT_CANNOT_BE_GIFT_CARD';
    public const PARENT_PRODUCT_VARIANT_CANNOT_REQUIRE_SELLING_PLAN = 'PARENT_PRODUCT_VARIANT_CANNOT_REQUIRE_SELLING_PLAN';
    public const PARENT_REQUIRED = 'PARENT_REQUIRED';
    public const PRODUCT_EXPANDER_APP_OWNERSHIP_ALREADY_EXISTS = 'PRODUCT_EXPANDER_APP_OWNERSHIP_ALREADY_EXISTS';
    public const PRODUCT_VARIANTS_NOT_COMPONENTS = 'PRODUCT_VARIANTS_NOT_COMPONENTS';
    public const PRODUCT_VARIANTS_NOT_FOUND = 'PRODUCT_VARIANTS_NOT_FOUND';
    public const PRODUCT_VARIANT_RELATIONSHIP_TYPE_CONFLICT = 'PRODUCT_VARIANT_RELATIONSHIP_TYPE_CONFLICT';
    public const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';
    public const UNSUPPORTED_MULTIPACK_RELATIONSHIP = 'UNSUPPORTED_MULTIPACK_RELATIONSHIP';
    public const UPDATE_PARENT_VARIANT_PRICE_REQUIRED = 'UPDATE_PARENT_VARIANT_PRICE_REQUIRED';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
