<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class ProductOptionUpdateUserErrorCode
{
    public const CANNOT_COMBINE_LINKED_AND_NONLINKED_OPTION_VALUES = 'CANNOT_COMBINE_LINKED_AND_NONLINKED_OPTION_VALUES';
    public const CANNOT_CREATE_VARIANTS_ABOVE_LIMIT = 'CANNOT_CREATE_VARIANTS_ABOVE_LIMIT';
    public const CANNOT_DELETE_ALL_OPTION_VALUES_IN_OPTION = 'CANNOT_DELETE_ALL_OPTION_VALUES_IN_OPTION';
    public const CANNOT_LEAVE_OPTIONS_WITHOUT_VARIANTS = 'CANNOT_LEAVE_OPTIONS_WITHOUT_VARIANTS';
    public const CANNOT_MAKE_CHANGES_IF_VARIANT_IS_MISSING_REQUIRED_SKU = 'CANNOT_MAKE_CHANGES_IF_VARIANT_IS_MISSING_REQUIRED_SKU';
    public const DUPLICATED_OPTION_VALUE = 'DUPLICATED_OPTION_VALUE';
    public const DUPLICATE_LINKED_OPTION = 'DUPLICATE_LINKED_OPTION';
    public const INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION = 'INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION';
    public const INVALID_NAME = 'INVALID_NAME';
    public const INVALID_POSITION = 'INVALID_POSITION';
    public const KEY_MISSING_IN_INPUT = 'KEY_MISSING_IN_INPUT';
    public const LINKED_METAFIELD_DEFINITION_NOT_FOUND = 'LINKED_METAFIELD_DEFINITION_NOT_FOUND';
    public const LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP = 'LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP';
    public const LINKED_OPTION_UPDATE_MISSING_VALUES = 'LINKED_OPTION_UPDATE_MISSING_VALUES';
    public const NO_KEY_ON_CREATE = 'NO_KEY_ON_CREATE';
    public const OPTION_ALREADY_EXISTS = 'OPTION_ALREADY_EXISTS';
    public const OPTION_DOES_NOT_EXIST = 'OPTION_DOES_NOT_EXIST';
    public const OPTION_LINKED_METAFIELD_ALREADY_TAKEN = 'OPTION_LINKED_METAFIELD_ALREADY_TAKEN';
    public const OPTION_NAME_TOO_LONG = 'OPTION_NAME_TOO_LONG';
    public const OPTION_VALUES_OVER_LIMIT = 'OPTION_VALUES_OVER_LIMIT';
    public const OPTION_VALUE_ALREADY_EXISTS = 'OPTION_VALUE_ALREADY_EXISTS';
    public const OPTION_VALUE_CONFLICTING_OPERATION = 'OPTION_VALUE_CONFLICTING_OPERATION';
    public const OPTION_VALUE_DOES_NOT_EXIST = 'OPTION_VALUE_DOES_NOT_EXIST';
    public const OPTION_VALUE_HAS_VARIANTS = 'OPTION_VALUE_HAS_VARIANTS';
    public const OPTION_VALUE_NAME_TOO_LONG = 'OPTION_VALUE_NAME_TOO_LONG';
    public const PRODUCT_DOES_NOT_EXIST = 'PRODUCT_DOES_NOT_EXIST';
    public const PRODUCT_SUSPENDED = 'PRODUCT_SUSPENDED';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
