<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class ProductOptionsCreateUserErrorCode
{
    public const CANNOT_COMBINE_LINKED_METAFIELD_AND_OPTION_VALUES = 'CANNOT_COMBINE_LINKED_METAFIELD_AND_OPTION_VALUES';
    public const CANNOT_MAKE_CHANGES_IF_VARIANT_IS_MISSING_REQUIRED_SKU = 'CANNOT_MAKE_CHANGES_IF_VARIANT_IS_MISSING_REQUIRED_SKU';
    public const DUPLICATED_OPTION_NAME = 'DUPLICATED_OPTION_NAME';
    public const DUPLICATED_OPTION_VALUE = 'DUPLICATED_OPTION_VALUE';
    public const DUPLICATE_LINKED_OPTION = 'DUPLICATE_LINKED_OPTION';
    public const INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION = 'INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION';
    public const LINKED_METAFIELD_DEFINITION_NOT_FOUND = 'LINKED_METAFIELD_DEFINITION_NOT_FOUND';
    public const LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP = 'LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP';
    public const MISSING_METAFIELD_VALUES_FOR_LINKED_OPTION = 'MISSING_METAFIELD_VALUES_FOR_LINKED_OPTION';
    public const NEW_OPTION_WITHOUT_VALUE_FOR_EXISTING_VARIANTS = 'NEW_OPTION_WITHOUT_VALUE_FOR_EXISTING_VARIANTS';
    public const OPTIONS_OVER_LIMIT = 'OPTIONS_OVER_LIMIT';
    public const OPTION_ALREADY_EXISTS = 'OPTION_ALREADY_EXISTS';
    public const OPTION_LINKED_METAFIELD_ALREADY_TAKEN = 'OPTION_LINKED_METAFIELD_ALREADY_TAKEN';
    public const OPTION_NAME_MISSING = 'OPTION_NAME_MISSING';
    public const OPTION_POSITION_MISSING = 'OPTION_POSITION_MISSING';
    public const OPTION_VALUES_MISSING = 'OPTION_VALUES_MISSING';
    public const OPTION_VALUES_OVER_LIMIT = 'OPTION_VALUES_OVER_LIMIT';
    public const POSITION_OUT_OF_BOUNDS = 'POSITION_OUT_OF_BOUNDS';
    public const PRODUCT_DOES_NOT_EXIST = 'PRODUCT_DOES_NOT_EXIST';
    public const PRODUCT_SUSPENDED = 'PRODUCT_SUSPENDED';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
