<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class QuantityRuleUserErrorCode
{
    public const BLANK = 'BLANK';
    public const CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES = 'CATALOG_CONTEXT_DOES_NOT_SUPPORT_QUANTITY_RULES';
    public const DUPLICATE_INPUT_FOR_VARIANT = 'DUPLICATE_INPUT_FOR_VARIANT';
    public const GENERIC_ERROR = 'GENERIC_ERROR';
    public const GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO';
    public const INCREMENT_IS_GREATER_THAN_MINIMUM = 'INCREMENT_IS_GREATER_THAN_MINIMUM';
    public const INCREMENT_NOT_A_MULTIPLE_OF_QUANTITY_PRICE_BREAK_MINIMUM = 'INCREMENT_NOT_A_MULTIPLE_OF_QUANTITY_PRICE_BREAK_MINIMUM';
    public const MAXIMUM_IS_LOWER_THAN_QUANTITY_PRICE_BREAK_MINIMUM = 'MAXIMUM_IS_LOWER_THAN_QUANTITY_PRICE_BREAK_MINIMUM';
    public const MAXIMUM_NOT_MULTIPLE_OF_INCREMENT = 'MAXIMUM_NOT_MULTIPLE_OF_INCREMENT';
    public const MINIMUM_IS_GREATER_THAN_MAXIMUM = 'MINIMUM_IS_GREATER_THAN_MAXIMUM';
    public const MINIMUM_IS_HIGHER_THAN_QUANTITY_PRICE_BREAK_MINIMUM = 'MINIMUM_IS_HIGHER_THAN_QUANTITY_PRICE_BREAK_MINIMUM';
    public const MINIMUM_NOT_MULTIPLE_OF_INCREMENT = 'MINIMUM_NOT_MULTIPLE_OF_INCREMENT';
    public const PRICE_LIST_DOES_NOT_EXIST = 'PRICE_LIST_DOES_NOT_EXIST';
    public const PRODUCT_VARIANT_DOES_NOT_EXIST = 'PRODUCT_VARIANT_DOES_NOT_EXIST';
    public const VARIANT_QUANTITY_RULE_DOES_NOT_EXIST = 'VARIANT_QUANTITY_RULE_DOES_NOT_EXIST';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
