<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class SellingPlanGroupUserErrorCode
{
    public const BILLING_AND_DELIVERY_POLICY_TYPES_MUST_BE_THE_SAME = 'BILLING_AND_DELIVERY_POLICY_TYPES_MUST_BE_THE_SAME';
    public const BILLING_POLICY_INTERVAL_TOO_LARGE = 'BILLING_POLICY_INTERVAL_TOO_LARGE';
    public const BLANK = 'BLANK';
    public const CHECKOUT_CHARGE_VALUE_AND_TYPE_MUST_MATCH = 'CHECKOUT_CHARGE_VALUE_AND_TYPE_MUST_MATCH';
    public const DELIVERY_POLICY_INTERVAL_TOO_LARGE = 'DELIVERY_POLICY_INTERVAL_TOO_LARGE';
    public const EQUAL_TO = 'EQUAL_TO';
    public const ERROR_ADDING_RESOURCE_TO_GROUP = 'ERROR_ADDING_RESOURCE_TO_GROUP';
    public const FULFILLMENT_EXACT_TIME_NOT_ALLOWED = 'FULFILLMENT_EXACT_TIME_NOT_ALLOWED';
    public const FULFILLMENT_EXACT_TIME_REQUIRED = 'FULFILLMENT_EXACT_TIME_REQUIRED';
    public const GREATER_THAN = 'GREATER_THAN';
    public const GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO';
    public const GROUP_COULD_NOT_BE_DELETED = 'GROUP_COULD_NOT_BE_DELETED';
    public const GROUP_DOES_NOT_EXIST = 'GROUP_DOES_NOT_EXIST';
    public const INCLUSION = 'INCLUSION';
    public const INVALID = 'INVALID';
    public const LESS_THAN = 'LESS_THAN';
    public const LESS_THAN_OR_EQUAL_TO = 'LESS_THAN_OR_EQUAL_TO';
    public const NOT_A_NUMBER = 'NOT_A_NUMBER';
    public const NOT_FOUND = 'NOT_FOUND';
    public const ONLY_NEED_ONE_BILLING_POLICY_TYPE = 'ONLY_NEED_ONE_BILLING_POLICY_TYPE';
    public const ONLY_NEED_ONE_CHECKOUT_CHARGE_VALUE = 'ONLY_NEED_ONE_CHECKOUT_CHARGE_VALUE';
    public const ONLY_NEED_ONE_DELIVERY_POLICY_TYPE = 'ONLY_NEED_ONE_DELIVERY_POLICY_TYPE';
    public const ONLY_NEED_ONE_PRICING_POLICY_TYPE = 'ONLY_NEED_ONE_PRICING_POLICY_TYPE';
    public const ONLY_NEED_ONE_PRICING_POLICY_VALUE = 'ONLY_NEED_ONE_PRICING_POLICY_VALUE';
    public const ONLY_ONE_OF_FIXED_OR_RECURRING_BILLING = 'ONLY_ONE_OF_FIXED_OR_RECURRING_BILLING';
    public const ONLY_ONE_OF_FIXED_OR_RECURRING_DELIVERY = 'ONLY_ONE_OF_FIXED_OR_RECURRING_DELIVERY';
    public const PLAN_DOES_NOT_EXIST = 'PLAN_DOES_NOT_EXIST';
    public const PLAN_ID_MUST_BE_SPECIFIED_TO_UPDATE = 'PLAN_ID_MUST_BE_SPECIFIED_TO_UPDATE';
    public const PRESENT = 'PRESENT';
    public const PRICING_POLICY_ADJUSTMENT_VALUE_AND_TYPE_MUST_MATCH = 'PRICING_POLICY_ADJUSTMENT_VALUE_AND_TYPE_MUST_MATCH';
    public const PRODUCT_DOES_NOT_EXIST = 'PRODUCT_DOES_NOT_EXIST';
    public const PRODUCT_VARIANT_DOES_NOT_EXIST = 'PRODUCT_VARIANT_DOES_NOT_EXIST';
    public const REMAINING_BALANCE_CHARGE_EXACT_TIME_NOT_ALLOWED = 'REMAINING_BALANCE_CHARGE_EXACT_TIME_NOT_ALLOWED';
    public const REMAINING_BALANCE_CHARGE_EXACT_TIME_REQUIRED = 'REMAINING_BALANCE_CHARGE_EXACT_TIME_REQUIRED';
    public const REMAINING_BALANCE_CHARGE_TIME_AFTER_CHECKOUT_MUST_BE_GREATER_THAN_ZERO = 'REMAINING_BALANCE_CHARGE_TIME_AFTER_CHECKOUT_MUST_BE_GREATER_THAN_ZERO';
    public const REMAINING_BALANCE_CHARGE_TRIGGER_NO_REMAINING_BALANCE_ON_PARTIAL_PERCENTAGE_CHECKOUT_CHARGE = 'REMAINING_BALANCE_CHARGE_TRIGGER_NO_REMAINING_BALANCE_ON_PARTIAL_PERCENTAGE_CHECKOUT_CHARGE';
    public const REMAINING_BALANCE_CHARGE_TRIGGER_NO_REMAINING_BALANCE_ON_PRICE_CHECKOUT_CHARGE = 'REMAINING_BALANCE_CHARGE_TRIGGER_NO_REMAINING_BALANCE_ON_PRICE_CHECKOUT_CHARGE';
    public const REMAINING_BALANCE_CHARGE_TRIGGER_ON_FULL_CHECKOUT = 'REMAINING_BALANCE_CHARGE_TRIGGER_ON_FULL_CHECKOUT';
    public const RESOURCE_LIST_CONTAINS_INVALID_IDS = 'RESOURCE_LIST_CONTAINS_INVALID_IDS';
    public const SELLING_PLAN_ANCHORS_NOT_ALLOWED = 'SELLING_PLAN_ANCHORS_NOT_ALLOWED';
    public const SELLING_PLAN_ANCHORS_REQUIRED = 'SELLING_PLAN_ANCHORS_REQUIRED';
    public const SELLING_PLAN_BILLING_AND_DELIVERY_POLICY_ANCHORS_MUST_BE_EQUAL = 'SELLING_PLAN_BILLING_AND_DELIVERY_POLICY_ANCHORS_MUST_BE_EQUAL';
    public const SELLING_PLAN_BILLING_CYCLE_MUST_BE_A_MULTIPLE_OF_DELIVERY_CYCLE = 'SELLING_PLAN_BILLING_CYCLE_MUST_BE_A_MULTIPLE_OF_DELIVERY_CYCLE';
    public const SELLING_PLAN_BILLING_POLICY_MISSING = 'SELLING_PLAN_BILLING_POLICY_MISSING';
    public const SELLING_PLAN_COUNT_LOWER_BOUND = 'SELLING_PLAN_COUNT_LOWER_BOUND';
    public const SELLING_PLAN_COUNT_UPPER_BOUND = 'SELLING_PLAN_COUNT_UPPER_BOUND';
    public const SELLING_PLAN_DELIVERY_POLICY_MISSING = 'SELLING_PLAN_DELIVERY_POLICY_MISSING';
    public const SELLING_PLAN_DUPLICATE_NAME = 'SELLING_PLAN_DUPLICATE_NAME';
    public const SELLING_PLAN_DUPLICATE_OPTIONS = 'SELLING_PLAN_DUPLICATE_OPTIONS';
    public const SELLING_PLAN_FIXED_PRICING_POLICIES_LIMIT = 'SELLING_PLAN_FIXED_PRICING_POLICIES_LIMIT';
    public const SELLING_PLAN_MAX_CYCLES_MUST_BE_GREATER_THAN_MIN_CYCLES = 'SELLING_PLAN_MAX_CYCLES_MUST_BE_GREATER_THAN_MIN_CYCLES';
    public const SELLING_PLAN_MISSING_OPTION2_LABEL_ON_PARENT_GROUP = 'SELLING_PLAN_MISSING_OPTION2_LABEL_ON_PARENT_GROUP';
    public const SELLING_PLAN_MISSING_OPTION3_LABEL_ON_PARENT_GROUP = 'SELLING_PLAN_MISSING_OPTION3_LABEL_ON_PARENT_GROUP';
    public const SELLING_PLAN_OPTION2_REQUIRED_AS_DEFINED_ON_PARENT_GROUP = 'SELLING_PLAN_OPTION2_REQUIRED_AS_DEFINED_ON_PARENT_GROUP';
    public const SELLING_PLAN_OPTION3_REQUIRED_AS_DEFINED_ON_PARENT_GROUP = 'SELLING_PLAN_OPTION3_REQUIRED_AS_DEFINED_ON_PARENT_GROUP';
    public const SELLING_PLAN_PRICING_POLICIES_LIMIT = 'SELLING_PLAN_PRICING_POLICIES_LIMIT';
    public const SELLING_PLAN_PRICING_POLICIES_MUST_CONTAIN_A_FIXED_PRICING_POLICY = 'SELLING_PLAN_PRICING_POLICIES_MUST_CONTAIN_A_FIXED_PRICING_POLICY';
    public const TAKEN = 'TAKEN';
    public const TOO_BIG = 'TOO_BIG';
    public const TOO_LONG = 'TOO_LONG';
    public const TOO_SHORT = 'TOO_SHORT';
    public const WRONG_LENGTH = 'WRONG_LENGTH';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
