<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class ShopifyPaymentsTransactionType
{
    public const ADJUSTMENT = 'ADJUSTMENT';
    public const ANOMALY_CREDIT = 'ANOMALY_CREDIT';
    public const ANOMALY_CREDIT_REVERSAL = 'ANOMALY_CREDIT_REVERSAL';
    public const ANOMALY_DEBIT = 'ANOMALY_DEBIT';
    public const ANOMALY_DEBIT_REVERSAL = 'ANOMALY_DEBIT_REVERSAL';
    public const APPLICATION_FEE_REFUND = 'APPLICATION_FEE_REFUND';
    public const BALANCE_TRANSFER_INBOUND = 'BALANCE_TRANSFER_INBOUND';
    public const BILLING_DEBIT = 'BILLING_DEBIT';
    public const BILLING_DEBIT_REVERSAL = 'BILLING_DEBIT_REVERSAL';
    public const CHANNEL_CREDIT = 'CHANNEL_CREDIT';
    public const CHANNEL_CREDIT_REVERSAL = 'CHANNEL_CREDIT_REVERSAL';
    public const CHANNEL_PROMOTION_CREDIT = 'CHANNEL_PROMOTION_CREDIT';
    public const CHANNEL_PROMOTION_CREDIT_REVERSAL = 'CHANNEL_PROMOTION_CREDIT_REVERSAL';
    public const CHANNEL_TRANSFER_CREDIT = 'CHANNEL_TRANSFER_CREDIT';
    public const CHANNEL_TRANSFER_CREDIT_REVERSAL = 'CHANNEL_TRANSFER_CREDIT_REVERSAL';
    public const CHANNEL_TRANSFER_DEBIT = 'CHANNEL_TRANSFER_DEBIT';
    public const CHANNEL_TRANSFER_DEBIT_REVERSAL = 'CHANNEL_TRANSFER_DEBIT_REVERSAL';
    public const CHARGE = 'CHARGE';
    public const CHARGEBACK_PROTECTION_CREDIT = 'CHARGEBACK_PROTECTION_CREDIT';
    public const CHARGEBACK_PROTECTION_CREDIT_REVERSAL = 'CHARGEBACK_PROTECTION_CREDIT_REVERSAL';
    public const CHARGEBACK_PROTECTION_DEBIT = 'CHARGEBACK_PROTECTION_DEBIT';
    public const CHARGEBACK_PROTECTION_DEBIT_REVERSAL = 'CHARGEBACK_PROTECTION_DEBIT_REVERSAL';
    public const CHARGE_ADJUSTMENT = 'CHARGE_ADJUSTMENT';
    public const COLLECTIONS_CREDIT = 'COLLECTIONS_CREDIT';
    public const COLLECTIONS_CREDIT_REVERSAL = 'COLLECTIONS_CREDIT_REVERSAL';
    public const CUSTOMS_DUTY = 'CUSTOMS_DUTY';
    public const CUSTOMS_DUTY_ADJUSTMENT = 'CUSTOMS_DUTY_ADJUSTMENT';
    public const DISPUTE_REVERSAL = 'DISPUTE_REVERSAL';
    public const DISPUTE_WITHDRAWAL = 'DISPUTE_WITHDRAWAL';
    public const IMPORT_TAX = 'IMPORT_TAX';
    public const IMPORT_TAX_ADJUSTMENT = 'IMPORT_TAX_ADJUSTMENT';
    public const MARKETPLACE_FEE_CREDIT = 'MARKETPLACE_FEE_CREDIT';
    public const MARKETPLACE_FEE_CREDIT_REVERSAL = 'MARKETPLACE_FEE_CREDIT_REVERSAL';
    public const MARKETS_PRO_CREDIT = 'MARKETS_PRO_CREDIT';
    public const MERCHANT_GOODWILL_CREDIT = 'MERCHANT_GOODWILL_CREDIT';
    public const MERCHANT_GOODWILL_CREDIT_REVERSAL = 'MERCHANT_GOODWILL_CREDIT_REVERSAL';
    public const MERCHANT_TO_MERCHANT_CREDIT = 'MERCHANT_TO_MERCHANT_CREDIT';
    public const MERCHANT_TO_MERCHANT_CREDIT_REVERSAL = 'MERCHANT_TO_MERCHANT_CREDIT_REVERSAL';
    public const MERCHANT_TO_MERCHANT_DEBIT = 'MERCHANT_TO_MERCHANT_DEBIT';
    public const MERCHANT_TO_MERCHANT_DEBIT_REVERSAL = 'MERCHANT_TO_MERCHANT_DEBIT_REVERSAL';
    public const PROMOTION_CREDIT = 'PROMOTION_CREDIT';
    public const PROMOTION_CREDIT_REVERSAL = 'PROMOTION_CREDIT_REVERSAL';
    public const REFUND = 'REFUND';
    public const REFUND_ADJUSTMENT = 'REFUND_ADJUSTMENT';
    public const REFUND_FAILURE = 'REFUND_FAILURE';
    public const RESERVED_FUNDS = 'RESERVED_FUNDS';
    public const RESERVED_FUNDS_REVERSAL = 'RESERVED_FUNDS_REVERSAL';
    public const RESERVED_FUNDS_WITHDRAWAL = 'RESERVED_FUNDS_WITHDRAWAL';
    public const RISK_REVERSAL = 'RISK_REVERSAL';
    public const RISK_WITHDRAWAL = 'RISK_WITHDRAWAL';
    public const SELLER_PROTECTION_CREDIT = 'SELLER_PROTECTION_CREDIT';
    public const SELLER_PROTECTION_CREDIT_REVERSAL = 'SELLER_PROTECTION_CREDIT_REVERSAL';
    public const SHIPPING_LABEL = 'SHIPPING_LABEL';
    public const SHIPPING_LABEL_ADJUSTMENT = 'SHIPPING_LABEL_ADJUSTMENT';
    public const SHIPPING_OTHER_CARRIER_CHARGE_ADJUSTMENT = 'SHIPPING_OTHER_CARRIER_CHARGE_ADJUSTMENT';
    public const SHIPPING_RETURN_TO_ORIGIN_ADJUSTMENT = 'SHIPPING_RETURN_TO_ORIGIN_ADJUSTMENT';
    public const SHOPIFY_COLLECTIVE_CREDIT = 'SHOPIFY_COLLECTIVE_CREDIT';
    public const SHOPIFY_COLLECTIVE_CREDIT_REVERSAL = 'SHOPIFY_COLLECTIVE_CREDIT_REVERSAL';
    public const SHOPIFY_COLLECTIVE_DEBIT = 'SHOPIFY_COLLECTIVE_DEBIT';
    public const SHOPIFY_COLLECTIVE_DEBIT_REVERSAL = 'SHOPIFY_COLLECTIVE_DEBIT_REVERSAL';
    public const SHOPIFY_SOURCE_CREDIT = 'SHOPIFY_SOURCE_CREDIT';
    public const SHOPIFY_SOURCE_CREDIT_REVERSAL = 'SHOPIFY_SOURCE_CREDIT_REVERSAL';
    public const SHOPIFY_SOURCE_DEBIT = 'SHOPIFY_SOURCE_DEBIT';
    public const SHOPIFY_SOURCE_DEBIT_REVERSAL = 'SHOPIFY_SOURCE_DEBIT_REVERSAL';
    public const SHOP_CASH_BILLING_DEBIT = 'SHOP_CASH_BILLING_DEBIT';
    public const SHOP_CASH_BILLING_DEBIT_REVERSAL = 'SHOP_CASH_BILLING_DEBIT_REVERSAL';
    public const SHOP_CASH_CAMPAIGN_BILLING_CREDIT = 'SHOP_CASH_CAMPAIGN_BILLING_CREDIT';
    public const SHOP_CASH_CAMPAIGN_BILLING_CREDIT_REVERSAL = 'SHOP_CASH_CAMPAIGN_BILLING_CREDIT_REVERSAL';
    public const SHOP_CASH_CAMPAIGN_BILLING_DEBIT = 'SHOP_CASH_CAMPAIGN_BILLING_DEBIT';
    public const SHOP_CASH_CAMPAIGN_BILLING_DEBIT_REVERSAL = 'SHOP_CASH_CAMPAIGN_BILLING_DEBIT_REVERSAL';
    public const SHOP_CASH_CREDIT = 'SHOP_CASH_CREDIT';
    public const SHOP_CASH_CREDIT_REVERSAL = 'SHOP_CASH_CREDIT_REVERSAL';
    public const SHOP_CASH_REFUND_DEBIT = 'SHOP_CASH_REFUND_DEBIT';
    public const SHOP_CASH_REFUND_DEBIT_REVERSAL = 'SHOP_CASH_REFUND_DEBIT_REVERSAL';
    public const STRIPE_FEE = 'STRIPE_FEE';
    public const TAX_ADJUSTMENT_CREDIT = 'TAX_ADJUSTMENT_CREDIT';
    public const TAX_ADJUSTMENT_CREDIT_REVERSAL = 'TAX_ADJUSTMENT_CREDIT_REVERSAL';
    public const TAX_ADJUSTMENT_DEBIT = 'TAX_ADJUSTMENT_DEBIT';
    public const TAX_ADJUSTMENT_DEBIT_REVERSAL = 'TAX_ADJUSTMENT_DEBIT_REVERSAL';
    public const TRANSFER = 'TRANSFER';
    public const TRANSFER_CANCEL = 'TRANSFER_CANCEL';
    public const TRANSFER_FAILURE = 'TRANSFER_FAILURE';
    public const TRANSFER_REFUND = 'TRANSFER_REFUND';
    public const VAT_REFUND_CREDIT = 'VAT_REFUND_CREDIT';
    public const VAT_REFUND_CREDIT_REVERSAL = 'VAT_REFUND_CREDIT_REVERSAL';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
