<?php declare(strict_types=1);

namespace App\Domain\Orders\GraphQL\Shopify\Stable\Types;

class SubscriptionDraftErrorCode
{
    public const ALREADY_REMOVED = 'ALREADY_REMOVED';
    public const BILLING_CYCLE_ABSENT = 'BILLING_CYCLE_ABSENT';
    public const BILLING_CYCLE_CONTRACT_DRAFT_BILLING_POLICY_INVALID = 'BILLING_CYCLE_CONTRACT_DRAFT_BILLING_POLICY_INVALID';
    public const BILLING_CYCLE_CONTRACT_DRAFT_DELIVERY_POLICY_INVALID = 'BILLING_CYCLE_CONTRACT_DRAFT_DELIVERY_POLICY_INVALID';
    public const BILLING_CYCLE_PRESENT = 'BILLING_CYCLE_PRESENT';
    public const BLANK = 'BLANK';
    public const COMMITTED = 'COMMITTED';
    public const CONCATENATION_BILLING_CYCLE_CONTRACT_DRAFT_REQUIRED = 'CONCATENATION_BILLING_CYCLE_CONTRACT_DRAFT_REQUIRED';
    public const CURRENCY_NOT_ENABLED = 'CURRENCY_NOT_ENABLED';
    public const CUSTOMER_DOES_NOT_EXIST = 'CUSTOMER_DOES_NOT_EXIST';
    public const CUSTOMER_MISMATCH = 'CUSTOMER_MISMATCH';
    public const CUSTOMER_REDACTED = 'CUSTOMER_REDACTED';
    public const CYCLE_DISCOUNTS_UNIQUE_AFTER_CYCLE = 'CYCLE_DISCOUNTS_UNIQUE_AFTER_CYCLE';
    public const CYCLE_INDEX_OUT_OF_RANGE = 'CYCLE_INDEX_OUT_OF_RANGE';
    public const CYCLE_SELECTOR_VALIDATE_ONE_OF = 'CYCLE_SELECTOR_VALIDATE_ONE_OF';
    public const CYCLE_START_DATE_OUT_OF_RANGE = 'CYCLE_START_DATE_OUT_OF_RANGE';
    public const DELIVERY_METHOD_REQUIRED = 'DELIVERY_METHOD_REQUIRED';
    public const DELIVERY_MUST_BE_MULTIPLE_OF_BILLING = 'DELIVERY_MUST_BE_MULTIPLE_OF_BILLING';
    public const DUPLICATE_CONCATENATED_CONTRACTS = 'DUPLICATE_CONCATENATED_CONTRACTS';
    public const EXCEEDED_MAX_CONCATENATED_CONTRACTS = 'EXCEEDED_MAX_CONCATENATED_CONTRACTS';
    public const GREATER_THAN = 'GREATER_THAN';
    public const GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO';
    public const HAS_FUTURE_EDITS = 'HAS_FUTURE_EDITS';
    public const INVALID = 'INVALID';
    public const INVALID_ADJUSTMENT_TYPE = 'INVALID_ADJUSTMENT_TYPE';
    public const INVALID_ADJUSTMENT_VALUE = 'INVALID_ADJUSTMENT_VALUE';
    public const INVALID_BILLING_DATE = 'INVALID_BILLING_DATE';
    public const INVALID_LINES = 'INVALID_LINES';
    public const INVALID_NOTE_LENGTH = 'INVALID_NOTE_LENGTH';
    public const LESS_THAN = 'LESS_THAN';
    public const LESS_THAN_OR_EQUAL_TO = 'LESS_THAN_OR_EQUAL_TO';
    public const MISSING_LOCAL_DELIVERY_OPTIONS = 'MISSING_LOCAL_DELIVERY_OPTIONS';
    public const NOT_AN_INTEGER = 'NOT_AN_INTEGER';
    public const NOT_IN_RANGE = 'NOT_IN_RANGE';
    public const NO_ENTITLED_LINES = 'NO_ENTITLED_LINES';
    public const PRESENCE = 'PRESENCE';
    public const SELLING_PLAN_MAX_CYCLES_MUST_BE_GREATER_THAN_MIN_CYCLES = 'SELLING_PLAN_MAX_CYCLES_MUST_BE_GREATER_THAN_MIN_CYCLES';
    public const STALE_CONTRACT = 'STALE_CONTRACT';
    public const TOO_LONG = 'TOO_LONG';
    public const TOO_SHORT = 'TOO_SHORT';
    public const UPCOMING_CYCLE_LIMIT_EXCEEDED = 'UPCOMING_CYCLE_LIMIT_EXCEEDED';

    public static function endpoint(): string
    {
        return 'shopify-orders-2024-01';
    }

    public static function config(): string
    {
        return \Safe\realpath(__DIR__ . '/../../../../../../../sailor.php');
    }
}
