CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "store_settings" ("id" varchar not null, "name" varchar not null, "value" text not null, "is_secure" tinyint(1) not null default '0', "store_id" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE UNIQUE INDEX "store_settings_store_id_name_unique" on "store_settings" ("store_id", "name");
CREATE INDEX "store_settings_store_id_index" on "store_settings" ("store_id");
CREATE TABLE IF NOT EXISTS "trialables" ("id" varchar not null, "source_key" varchar not null default 'shopify', "source_id" varchar not null, "group_key" varchar, "status" varchar not null default 'init', "title" varchar, "subtitle" varchar, "image" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "expires_at" datetime, "trial_duration" integer not null default '7', primary key ("id"));
CREATE TABLE IF NOT EXISTS "products" ("id" varchar not null, "source" varchar not null default 'shopify', "source_id" varchar not null, "source_handle" varchar not null, "source_online_store_url" varchar not null, "title" varchar not null, "description" text not null, "type" varchar not null, "image_url" varchar not null, "is_gift_card" tinyint(1) not null, "requires_selling_plan" tinyint(1) not null, "tags" varchar, "vendor" varchar, "max_variant_price" integer, "min_variant_price" integer not null default '0', "data" text not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE UNIQUE INDEX "products_source_id_unique" on "products" ("source_id");
CREATE TABLE IF NOT EXISTS "product_variants" ("id" varchar not null, "product_id" varchar not null, "source" varchar not null default 'shopify', "source_id" varchar not null, "source_product_id" varchar not null, "title" varchar not null, "barcode" varchar, "sku" varchar, "requires_shipping" tinyint(1) not null default '1', "price" integer not null, "image_url" varchar not null, "unit_price" integer, "unit_price_measurement" text, "weight" float, "weight_unit" varchar, "data" text not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE UNIQUE INDEX "product_variants_source_id_unique" on "product_variants" ("source_id");
CREATE TABLE IF NOT EXISTS "orders_line_items" ("id" varchar not null, "source_id" varchar not null, "order_id" varchar not null, "quantity" integer not null, "status" varchar not null, "trialable_id" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "trial_group_id" varchar, "is_tbyb" tinyint(1) not null default '0', "selling_plan_id" varchar, "shop_currency" varchar not null default 'USD', "customer_currency" varchar not null default 'USD', "price_shop_amount" integer not null default '0', "price_customer_amount" integer not null default '0', "total_price_shop_amount" integer not null default '0', "total_price_customer_amount" integer not null default '0', "discount_shop_amount" integer not null default '0', "discount_customer_amount" integer not null default '0', "tax_shop_amount" integer not null default '0', "tax_customer_amount" integer not null default '0', "deposit_type" varchar, "deposit_value" integer, "deposit_shop_amount" integer, "deposit_customer_amount" integer, "source_order_id" varchar, "source_product_id" varchar, "source_variant_id" varchar, "product_title" varchar, "variant_title" varchar, "thumbnail" varchar, "decision_status" varchar not null default 'kept', "status_updated_by" varchar not null default 'shopify', "original_quantity" integer not null default '1', primary key ("id"));
CREATE TABLE IF NOT EXISTS "billings_app_usage_records" ("id" varchar not null, "subscription_line_item_id" varchar not null, "shopify_app_subscription_line_item_id" varchar not null, "description" varchar not null, "amount" integer not null, "amount_currency" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE INDEX "app_usage_subscription_line_item_id_index" on "billings_app_usage_records" ("subscription_line_item_id");
CREATE INDEX "app_usage_shopify_app_subscription_line_item_id_index" on "billings_app_usage_records" ("shopify_app_subscription_line_item_id");
CREATE TABLE billings_app_usage_configs (id VARCHAR(255) NOT NULL COLLATE "BINARY", store_id VARCHAR(255) NOT NULL COLLATE "BINARY", subscription_line_item_id VARCHAR(255) NOT NULL COLLATE "BINARY", description VARCHAR(255) NOT NULL COLLATE "BINARY", config CLOB NOT NULL COLLATE "BINARY", created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, "currency" varchar not null, "valid_from" datetime not null, "valid_to" datetime, PRIMARY KEY(id));
CREATE INDEX app_usage_config_store_id_index ON billings_app_usage_configs (store_id);
CREATE INDEX app_usage_config_subscription_line_item_id_index ON billings_app_usage_configs (subscription_line_item_id);
CREATE TABLE IF NOT EXISTS "shopify_webhook_data" ("id" varchar not null, "store_id" varchar not null, "topic" varchar not null, "data" text not null, "attributes" text not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE INDEX "shopify_webhook_data_store_id_index" on "shopify_webhook_data" ("store_id");
CREATE INDEX "shopify_webhook_data_topic_index" on "shopify_webhook_data" ("topic");
CREATE TABLE billings_subscription_line_items (id VARCHAR(255) NOT NULL, subscription_id VARCHAR(255) NOT NULL, shopify_app_subscription_id VARCHAR(255) NOT NULL, shopify_app_subscription_line_item_id VARCHAR(255) NOT NULL, terms VARCHAR(255) NOT NULL, usage_capped_amount INTEGER DEFAULT NULL, usage_capped_amount_currency VARCHAR(3) DEFAULT 'USD' NOT NULL --ISO 4217
, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, type VARCHAR(255) DEFAULT 'usage' NOT NULL, "recurring_amount" integer, "recurring_amount_currency" varchar not null default 'USD', PRIMARY KEY(id));
CREATE INDEX sub_line_items_subscription_id_index ON billings_subscription_line_items (subscription_id);
CREATE INDEX sub_line_items_shopify_app_subscription_id_index ON billings_subscription_line_items (shopify_app_subscription_id);
CREATE INDEX sub_line_items_shopify_app_subscription_line_item_id_index ON billings_subscription_line_items (shopify_app_subscription_line_item_id);
CREATE TABLE billings_subscriptions (id VARCHAR(255) NOT NULL, store_id VARCHAR(255) NOT NULL, shopify_app_subscription_id VARCHAR(255) NOT NULL, shopify_confirmation_url VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT 'pending' NOT NULL, activated_at DATETIME DEFAULT NULL, deactivated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, "current_period_end" datetime, "trial_days" integer not null default '0', "trial_period_end" datetime, "is_test" tinyint(1) not null default '0', "current_period_start" datetime, PRIMARY KEY(id));
CREATE INDEX subscriptions_shopify_app_subscription_id_index ON billings_subscriptions (shopify_app_subscription_id);
CREATE INDEX subscriptions_store_id_index ON billings_subscriptions (store_id);
CREATE TABLE IF NOT EXISTS "orders_trial_group" ("id" varchar not null, "order_id" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE TABLE IF NOT EXISTS "shopify_mandatory_webhooks" ("id" varchar not null, "store_id" varchar not null, "topic" varchar not null, "shopify_shop_id" varchar not null, "shopify_domain" varchar not null, "data" text not null, "status" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE INDEX "shopify_mandatory_webhooks_store_id_index" on "shopify_mandatory_webhooks" ("store_id");
CREATE INDEX "shopify_mandatory_webhooks_shopify_domain_index" on "shopify_mandatory_webhooks" ("shopify_domain");
CREATE TABLE shopify_jobs (id VARCHAR(255) NOT NULL COLLATE "BINARY", store_id VARCHAR(255) NOT NULL COLLATE "BINARY", shopify_job_id VARCHAR(255) NOT NULL COLLATE "BINARY", "query" VARCHAR(255) NOT NULL COLLATE "BINARY", domain VARCHAR(255) NOT NULL COLLATE "BINARY", export_file_url VARCHAR(255) DEFAULT NULL COLLATE "BINARY", status VARCHAR(255) NOT NULL COLLATE "BINARY", created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, type VARCHAR(255) DEFAULT 'query' NOT NULL COLLATE "BINARY", topic VARCHAR(255) NOT NULL COLLATE "BINARY", export_partial_file_url VARCHAR(255) DEFAULT NULL COLLATE "BINARY", error_code VARCHAR(255) DEFAULT NULL COLLATE "BINARY", PRIMARY KEY(id));
CREATE INDEX shopify_jobs_shopify_job_id_index ON shopify_jobs (shopify_job_id);
CREATE INDEX shopify_jobs_store_id_index ON shopify_jobs (store_id);
CREATE TABLE stores (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, owner_name VARCHAR(255) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL --ISO 4127
, primary_locale VARCHAR(2) DEFAULT NULL --ISO 639 two-letter language code
, address1 VARCHAR(255) DEFAULT NULL, address2 VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, country_code VARCHAR(3) DEFAULT NULL --ISO 3166-1 alpha-2
, country_name VARCHAR(255) DEFAULT NULL, iana_timezone VARCHAR(255) DEFAULT NULL, ecommerce_platform VARCHAR(255) DEFAULT 'shopify' NOT NULL, ecommerce_platform_store_id VARCHAR(255) NOT NULL, ecommerce_platform_plan VARCHAR(255) DEFAULT NULL, ecommerce_platform_plan_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, state_code VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX stores_name_index ON stores (name);
CREATE TABLE programs (id VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT 'Try Before You Buy' NOT NULL, store_id VARCHAR(255) NOT NULL, shopify_selling_plan_group_id VARCHAR(255) DEFAULT NULL, shopify_selling_plan_id VARCHAR(255) DEFAULT NULL, try_period_days INTEGER DEFAULT 7 NOT NULL, deposit_type VARCHAR(255) DEFAULT 'percentage' NOT NULL, deposit_value INTEGER DEFAULT 0 NOT NULL, min_tbyb_items INTEGER DEFAULT 1 NOT NULL, max_tbyb_items INTEGER DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, product_ids CLOB DEFAULT NULL, product_variant_ids CLOB DEFAULT NULL, currency VARCHAR(255) DEFAULT 'USD' NOT NULL, "drop_off_days" integer not null default '5', PRIMARY KEY(id));
CREATE INDEX programs_store_id_index ON programs (store_id);
CREATE TABLE IF NOT EXISTS "billings_tbyb_net_sales" ("id" varchar not null, "store_id" varchar not null, "date_start" date not null, "date_end" date not null, "time_range_start" datetime not null, "time_range_end" datetime not null, "currency" varchar not null, "tbyb_gross_sales" integer not null default '0', "tbyb_discounts" integer not null default '0', "tbyb_refunded_gross_sales" integer not null default '0', "tbyb_refunded_discounts" integer not null default '0', "tbyb_net_sales" integer not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "is_first_of_billing_period" tinyint(1) not null default '0', primary key ("id"));
CREATE INDEX "billings_tbyb_net_sales_store_id_index" on "billings_tbyb_net_sales" ("store_id");
CREATE TABLE orders_tbyb_net_sales (id VARCHAR(255) NOT NULL, store_id VARCHAR(255) NOT NULL, date_start DATE NOT NULL, date_end DATE NOT NULL, time_range_start DATETIME NOT NULL, time_range_end DATETIME NOT NULL, currency VARCHAR(255) NOT NULL, tbyb_gross_sales BIGINT DEFAULT 0 NOT NULL, tbyb_discounts BIGINT DEFAULT 0 NOT NULL, tbyb_refunded_gross_sales BIGINT DEFAULT 0 NOT NULL, tbyb_refunded_discounts BIGINT DEFAULT 0 NOT NULL, tbyb_net_sales BIGINT DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, "is_first_of_billing_period" tinyint(1) not null default '0', PRIMARY KEY(id));
CREATE INDEX orders_tbyb_net_sales_store_id_index ON orders_tbyb_net_sales (store_id);
CREATE TABLE billings_charges (id VARCHAR(255) NOT NULL, store_id VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, amount INTEGER NOT NULL, balance BIGINT DEFAULT 0 NOT NULL, is_billed BOOLEAN NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, "step_size" integer, "step_start_amount" integer, "step_end_amount" integer, "is_first_of_billing_period" tinyint(1) not null default '0', "time_range_start" datetime, "time_range_end" datetime, "tbyb_net_sale_id" varchar, "billed_at" datetime, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS "orders_returns" ("id" varchar not null, "source_id" varchar not null, "order_id" varchar not null, "store_id" varchar not null, "source_order_id" varchar not null, "shop_currency" varchar not null, "customer_currency" varchar not null, "name" varchar, "status" varchar not null, "total_quantity" integer not null default '0', "tbyb_gross_sales_shop_amount" integer not null default '0', "tbyb_gross_sales_customer_amount" integer not null default '0', "tbyb_discounts_shop_amount" integer not null default '0', "tbyb_discounts_customer_amount" integer not null default '0', "upfront_gross_sales_shop_amount" integer not null default '0', "upfront_gross_sales_customer_amount" integer not null default '0', "upfront_discounts_shop_amount" integer not null default '0', "upfront_discounts_customer_amount" integer not null default '0', "tbyb_tax_shop_amount" integer not null default '0', "tbyb_tax_customer_amount" integer not null default '0', "upfront_tax_shop_amount" integer not null default '0', "upfront_tax_customer_amount" integer not null default '0', "tbyb_total_shop_amount" integer not null default '0', "tbyb_total_customer_amount" integer not null default '0', "return_data" text not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, primary key ("id"));
CREATE UNIQUE INDEX "orders_returns_source_id_unique" on "orders_returns" ("source_id");
CREATE INDEX "orders_returns_order_id_index" on "orders_returns" ("order_id");
CREATE INDEX "orders_returns_store_id_index" on "orders_returns" ("store_id");
CREATE INDEX "orders_returns_source_order_id_index" on "orders_returns" ("source_order_id");
CREATE TABLE IF NOT EXISTS "orders_returns_line_items" ("id" varchar not null, "source_id" varchar not null, "order_return_id" varchar not null, "source_return_id" varchar not null, "line_item_id" varchar not null, "customer_note" varchar, "quantity" integer not null default '0', "return_reason" varchar, "return_reason_note" varchar, "shop_currency" varchar not null, "customer_currency" varchar not null, "gross_sales_shop_amount" integer not null, "gross_sales_customer_amount" integer not null, "discounts_shop_amount" integer not null, "discounts_customer_amount" integer not null, "tax_customer_amount" integer not null, "tax_shop_amount" integer not null, "return_line_item_data" text not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "is_tbyb" tinyint(1) not null, primary key ("id"));
CREATE UNIQUE INDEX "orders_returns_line_items_source_id_unique" on "orders_returns_line_items" ("source_id");
CREATE INDEX "orders_returns_line_items_order_return_id_index" on "orders_returns_line_items" ("order_return_id");
CREATE INDEX "orders_returns_line_items_source_return_id_index" on "orders_returns_line_items" ("source_return_id");
CREATE INDEX "orders_returns_line_items_line_item_id_index" on "orders_returns_line_items" ("line_item_id");
CREATE INDEX "orders_line_items_order_id_index" on "orders_line_items" ("order_id");
CREATE INDEX "orders_line_items_source_order_id_index" on "orders_line_items" ("source_order_id");
CREATE INDEX "orders_line_items_source_product_id_index" on "orders_line_items" ("source_product_id");
CREATE INDEX "orders_line_items_source_variant_id_index" on "orders_line_items" ("source_variant_id");
CREATE INDEX "billings_charges_store_id_index" on "billings_charges" ("store_id");
CREATE UNIQUE INDEX "orders_line_items_source_id_unique" on "orders_line_items" ("source_id");
CREATE INDEX "orders_trial_group_order_id_index" on "orders_trial_group" ("order_id");
CREATE UNIQUE INDEX "programs_shopify_selling_plan_id_unique" on "programs" ("shopify_selling_plan_id");
CREATE TABLE orders (id VARCHAR(255) NOT NULL, store_id VARCHAR(255) NOT NULL, source_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, order_data CLOB NOT NULL, blackcart_metadata CLOB DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, taxes_included BOOLEAN DEFAULT 0 NOT NULL, taxes_exempt BOOLEAN DEFAULT 0 NOT NULL, tags VARCHAR(255) DEFAULT '' NOT NULL, discount_codes VARCHAR(255) DEFAULT '' NOT NULL, test BOOLEAN DEFAULT 0 NOT NULL, payment_terms_id VARCHAR(255) DEFAULT NULL, payment_terms_name VARCHAR(255) DEFAULT NULL, payment_terms_type VARCHAR(255) DEFAULT NULL, shop_currency VARCHAR(255) DEFAULT 'USD' NOT NULL, customer_currency VARCHAR(255) DEFAULT 'USD' NOT NULL, total_shop_amount INTEGER DEFAULT 0 NOT NULL, total_customer_amount INTEGER DEFAULT 0 NOT NULL, outstanding_shop_amount INTEGER DEFAULT 0 NOT NULL, outstanding_customer_amount INTEGER DEFAULT 0 NOT NULL, original_tbyb_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, original_tbyb_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, original_upfront_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, original_upfront_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, original_total_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, original_total_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, original_tbyb_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, original_tbyb_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, original_upfront_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, original_upfront_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, original_total_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, original_total_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, tbyb_refund_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, tbyb_refund_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, upfront_refund_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, upfront_refund_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, total_order_level_refunds_shop_amount INTEGER DEFAULT 0 NOT NULL, total_order_level_refunds_customer_amount INTEGER DEFAULT 0 NOT NULL, tbyb_refund_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, tbyb_refund_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, upfront_refund_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, upfront_refund_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, tbyb_net_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, tbyb_net_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, upfront_net_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, upfront_net_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, total_net_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, total_net_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, completed_at DATETIME DEFAULT NULL, original_outstanding_shop_amount INTEGER DEFAULT 0 NOT NULL, original_outstanding_customer_amount INTEGER DEFAULT 0 NOT NULL, "assumed_delivery_merchant_email_sent_at" datetime, "trial_expires_at" datetime, PRIMARY KEY(id));
CREATE UNIQUE INDEX orders_source_id_unique ON orders (source_id);
CREATE INDEX orders_store_id_index ON orders (store_id);
CREATE TABLE orders_refunds (id VARCHAR(255) NOT NULL COLLATE "BINARY", source_refund_reference_id VARCHAR(255) DEFAULT NULL COLLATE "BINARY", order_id VARCHAR(255) NOT NULL COLLATE "BINARY", shop_currency VARCHAR(255) NOT NULL COLLATE "BINARY", customer_currency VARCHAR(255) NOT NULL COLLATE "BINARY", created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, tbyb_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, tbyb_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, tbyb_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, tbyb_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, upfront_gross_sales_shop_amount INTEGER DEFAULT 0 NOT NULL, upfront_gross_sales_customer_amount INTEGER DEFAULT 0 NOT NULL, upfront_discounts_shop_amount INTEGER DEFAULT 0 NOT NULL, upfront_discounts_customer_amount INTEGER DEFAULT 0 NOT NULL, order_level_refund_shop_amount INTEGER DEFAULT 0 NOT NULL, order_level_refund_customer_amount INTEGER DEFAULT 0 NOT NULL, store_id VARCHAR(255) DEFAULT NULL COLLATE "BINARY", "tbyb_total_shop_amount" integer, "tbyb_total_customer_amount" integer, "upfront_total_shop_amount" integer, "upfront_total_customer_amount" integer, "tbyb_deposit_shop_amount" integer not null, "tbyb_deposit_customer_amount" integer not null, "refunded_shop_amount" integer not null default '0', "refunded_customer_amount" integer not null default '0', "refund_data" text, PRIMARY KEY(id));
CREATE UNIQUE INDEX orders_refunds_source_id_unique ON orders_refunds (source_refund_reference_id);
CREATE INDEX orders_refunds_order_id_index ON orders_refunds (order_id);
CREATE TABLE orders_refund_line_items (id VARCHAR(255) NOT NULL COLLATE "BINARY", source_refund_reference_id VARCHAR(255) NOT NULL, line_item_id VARCHAR(255) NOT NULL COLLATE "BINARY", quantity INTEGER NOT NULL, shop_currency VARCHAR(255) NOT NULL COLLATE "BINARY", customer_currency VARCHAR(255) NOT NULL COLLATE "BINARY", gross_sales_shop_amount INTEGER NOT NULL, gross_sales_customer_amount INTEGER NOT NULL, discounts_shop_amount INTEGER NOT NULL, discounts_customer_amount INTEGER NOT NULL, is_tbyb BOOLEAN DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, tax_shop_amount INTEGER NOT NULL, tax_customer_amount INTEGER NOT NULL, total_shop_amount INTEGER NOT NULL, total_customer_amount INTEGER NOT NULL, "refund_id" varchar not null, "deposit_shop_amount" integer not null, "deposit_customer_amount" integer not null, PRIMARY KEY(id));
CREATE TABLE orders_transactions (id VARCHAR(255) NOT NULL COLLATE "BINARY", source_id VARCHAR(255) NOT NULL COLLATE "BINARY", order_id VARCHAR(255) NOT NULL COLLATE "BINARY", source_order_id VARCHAR(255) NOT NULL COLLATE "BINARY", store_id VARCHAR(255) NOT NULL COLLATE "BINARY", kind VARCHAR(255) NOT NULL COLLATE "BINARY", gateway VARCHAR(255) NOT NULL COLLATE "BINARY", payment_id VARCHAR(255) NOT NULL COLLATE "BINARY", parent_transaction_id VARCHAR(255) DEFAULT NULL COLLATE "BINARY", parent_transaction_source_id VARCHAR(255) DEFAULT NULL COLLATE "BINARY", customer_currency VARCHAR(255) NOT NULL COLLATE "BINARY", shop_currency VARCHAR(255) NOT NULL COLLATE "BINARY", customer_amount INTEGER NOT NULL, shop_amount INTEGER NOT NULL, unsettled_customer_amount INTEGER NOT NULL, unsettled_shop_amount INTEGER NOT NULL, status VARCHAR(255) NOT NULL COLLATE "BINARY", test BOOLEAN DEFAULT 0 NOT NULL, error_code VARCHAR(255) DEFAULT NULL COLLATE "BINARY", message VARCHAR(255) DEFAULT NULL COLLATE "BINARY", transaction_source_name VARCHAR(255) DEFAULT NULL COLLATE "BINARY", user_id VARCHAR(255) DEFAULT NULL COLLATE "BINARY", processed_at DATETIME DEFAULT NULL, authorization_expires_at DATETIME DEFAULT NULL, transaction_data CLOB NOT NULL COLLATE "BINARY", created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, "order_name" varchar, PRIMARY KEY(id));
CREATE INDEX orders_transactions_order_id_index ON orders_transactions (order_id);
CREATE INDEX orders_transactions_source_order_id_index ON orders_transactions (source_order_id);
CREATE INDEX orders_transactions_store_id_index ON orders_transactions (store_id);
CREATE UNIQUE INDEX orders_transactions_source_id_unique ON orders_transactions (source_id);
CREATE TABLE IF NOT EXISTS "stackkit_cloud_tasks" ("id" integer primary key autoincrement not null, "queue" varchar not null, "task_uuid" varchar not null, "name" varchar not null, "status" varchar not null, "metadata" text not null, "payload" text not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "stackkit_cloud_tasks_task_uuid_index" on "stackkit_cloud_tasks" ("task_uuid");
CREATE INDEX "stackkit_cloud_tasks_queue_index" on "stackkit_cloud_tasks" ("queue");
CREATE INDEX "stackkit_cloud_tasks_status_index" on "stackkit_cloud_tasks" ("status");
CREATE UNIQUE INDEX "stores_domain_deleted_at_unique" on "stores" ("domain", "deleted_at");
CREATE TABLE IF NOT EXISTS "payments_transactions" ("id" varchar not null, "source_id" varchar, "order_id" varchar not null, "store_id" varchar not null, "source_order_id" varchar not null, "shop_amount" integer not null, "shop_currency" varchar not null, "customer_amount" integer not null, "customer_currency" varchar not null, "status" varchar not null, "kind" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "captured_transaction_id" varchar, "parent_transaction_id" varchar, "captured_transaction_source_id" varchar, "parent_transaction_source_id" varchar, "authorization_expires_at" datetime, "transaction_source_name" varchar, primary key ("id"));
CREATE INDEX "payments_transactions_order_id_index" on "payments_transactions" ("order_id");
CREATE UNIQUE INDEX "payments_transactions_source_id_unique" on "payments_transactions" ("source_id");
CREATE INDEX "payments_transactions_source_order_id_index" on "payments_transactions" ("source_order_id");
CREATE INDEX "payments_transactions_store_id_index" on "payments_transactions" ("store_id");
INSERT INTO migrations VALUES(1,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(2,'2023_10_13_202847_create_stores_table',1);
INSERT INTO migrations VALUES(3,'2023_10_31_181839_create_store_settings_table',1);
INSERT INTO migrations VALUES(4,'2023_11_01_212015_create_programs_table',1);
INSERT INTO migrations VALUES(5,'2023_11_06_200026_trialbles',1);
INSERT INTO migrations VALUES(6,'2023_11_16_160549_add_product_ids_to_programs_table',1);
INSERT INTO migrations VALUES(7,'2023_11_28_012517_products_and_variants',1);
INSERT INTO migrations VALUES(8,'2023_11_28_054735_shopify_jobs_table',1);
INSERT INTO migrations VALUES(9,'2023_12_08_163812_orders_tables',1);
INSERT INTO migrations VALUES(10,'2023_12_11_184919_create_billings_tables',1);
INSERT INTO migrations VALUES(11,'2023_12_12_054735_add_domain_shopify_jobs_table',1);
INSERT INTO migrations VALUES(12,'2023_12_12_145942_remove_activate_timestamps_from_line_items',1);
INSERT INTO migrations VALUES(13,'2023_12_12_160122_add_subscription_line_item_type',1);
INSERT INTO migrations VALUES(14,'2023_12_12_192544_create_shopify_webhook_data',1);
INSERT INTO migrations VALUES(15,'2023_12_15_160122_add_recurring_sub_line_item_columns',1);
INSERT INTO migrations VALUES(16,'2023_12_18_160122_update_subscription_status_column',1);
INSERT INTO migrations VALUES(17,'2023_12_28_181839_add_shopify_shop_details_columns_to_stores_table',1);
INSERT INTO migrations VALUES(18,'2023_12_29_181839_add_shopify_shop_details_columns_to_stores_table',1);
INSERT INTO migrations VALUES(19,'2024_01_01_160100_add_currency_to_programs_table',1);
INSERT INTO migrations VALUES(20,'2024_01_02_083014_trial_groups',1);
INSERT INTO migrations VALUES(21,'2024_01_06_144535_add_shopify_mandatory_webhooks_table',1);
INSERT INTO migrations VALUES(22,'2024_01_08_164608_trial_duration',1);
INSERT INTO migrations VALUES(23,'2024_01_16_212635_add_topic_remove_callback_url_shopify_jobs_table',1);
INSERT INTO migrations VALUES(24,'2024_01_17_144822_nullable_columns_stores_table',1);
INSERT INTO migrations VALUES(25,'2024_01_18_192209_update_deposit_default_to_percentage',1);
INSERT INTO migrations VALUES(26,'2024_01_29_014542_create_refunds_table',1);
INSERT INTO migrations VALUES(27,'2024_02_05_204915_create_billings_charges_table',1);
INSERT INTO migrations VALUES(28,'2024_02_06_175129_order_updates_for_billing',1);
INSERT INTO migrations VALUES(29,'2024_02_06_193107_add_sum_columns_to_orders_refunds',1);
INSERT INTO migrations VALUES(30,'2024_02_06_200620_create_orders_refund_line_items_table',1);
INSERT INTO migrations VALUES(31,'2024_02_06_201412_create_orders_tbyb_net_sales_table',1);
INSERT INTO migrations VALUES(32,'2024_02_08_110512_create_billings_tbyb_net_sales_table',1);
INSERT INTO migrations VALUES(33,'2024_02_08_174026_add_store_id_to_orders_refunds_table',1);
INSERT INTO migrations VALUES(34,'2024_02_08_180732_remove_legacy_columns_orders_refunds',1);
INSERT INTO migrations VALUES(35,'2024_02_08_210934_remove_legacy_columns_orders_refund_line_items',1);
INSERT INTO migrations VALUES(36,'2024_02_10_232108_add_currency_valid_to_billings_app_usage_configs',1);
INSERT INTO migrations VALUES(37,'2024_02_12_160001_change_sale_columns_to_big_int',1);
INSERT INTO migrations VALUES(38,'2024_02_12_171138_change_balance_to_big_integer_billings_charges',1);
INSERT INTO migrations VALUES(39,'2024_02_15_032943_add_details_columns_to_billings_charges',1);
INSERT INTO migrations VALUES(40,'2024_02_20_161303_create_returns_and_returns_line_items',1);
INSERT INTO migrations VALUES(41,'2024_02_21_161243_add_billing_period_end_date_to_billings_subscriptions',1);
INSERT INTO migrations VALUES(42,'2024_02_23_192634_add_taxes_to_line_items',1);
INSERT INTO migrations VALUES(43,'2024_02_23_213142_create_payments_transactions_table',1);
INSERT INTO migrations VALUES(44,'2024_02_25_193801_new_orders_transactions_table',1);
INSERT INTO migrations VALUES(45,'2024_02_28_212202_add_completed_at_to_order',1);
INSERT INTO migrations VALUES(46,'2024_02_29_142901_selling_plan_fields_in_line_items_table',1);
INSERT INTO migrations VALUES(47,'2024_03_01_004553_add_original_outstanding_amount',1);
INSERT INTO migrations VALUES(48,'2024_03_05_080630_add_captured_transaction_id_to_payments_transactions',1);
INSERT INTO migrations VALUES(49,'2024_03_05_155522_product_variant_fields_in_line_items_table',1);
INSERT INTO migrations VALUES(50,'2024_03_06_220556_billings_tables_indices',1);
INSERT INTO migrations VALUES(51,'2024_03_06_220556_orders_tables_indices',1);
INSERT INTO migrations VALUES(52,'2024_03_06_220556_payments_tables_indices',1);
INSERT INTO migrations VALUES(53,'2024_03_06_220556_programs_tables_indices',1);
INSERT INTO migrations VALUES(54,'2024_03_08_023040_add_tax_columns_to_orders_refund_line_items',1);
INSERT INTO migrations VALUES(55,'2024_03_08_023255_add_total_refund_amount_to_orders_refund_line_items',1);
INSERT INTO migrations VALUES(56,'2024_03_08_151823_new_columns_outstanding_order_total_orders_table',1);
INSERT INTO migrations VALUES(57,'2024_03_08_202008_rename_order_level_refunds_in_orders_refunds',1);
INSERT INTO migrations VALUES(58,'2024_03_08_202130_rename_refund_id_in_orders_refund_line_items',1);
INSERT INTO migrations VALUES(59,'2024_03_08_202259_add_is_tbyb_to_orders_returns_line_items',1);
INSERT INTO migrations VALUES(60,'2024_03_08_231831_add_tbyb_upfront_totals_to_orders_refunds',1);
INSERT INTO migrations VALUES(61,'2024_03_11_041650_add_refund_id_to_orders_refund_line_items',1);
INSERT INTO migrations VALUES(62,'2024_03_11_129384_add_drop_off_days_to_programs',1);
INSERT INTO migrations VALUES(63,'2024_03_11_204405_add_deposit_amount_to_orders_refund_line_items',1);
INSERT INTO migrations VALUES(64,'2024_03_11_204603_add_deposit_total_amount_to_orders_refunds',1);
INSERT INTO migrations VALUES(65,'2024_03_12_121547_add_decision_status_order_line_items',1);
INSERT INTO migrations VALUES(66,'2024_03_14_183726_add_refunded_amount_to_orders_refunds_table',1);
INSERT INTO migrations VALUES(67,'2024_03_21_153236_transactions_add_source_id_columns',1);
INSERT INTO migrations VALUES(68,'2024_03_27_080752_add_assumed_delivery_merchant_email_sent_at_to_orders_table',1);
INSERT INTO migrations VALUES(69,'2024_04_03_120752_make_receipt_json_nullable_transactions_table',2);
INSERT INTO migrations VALUES(70,'2024_04_03_141028_drop_receipt_json_from_transactions_table',2);
INSERT INTO migrations VALUES(71,'2024_04_05_185527_add_status_updated_by_to_orders_line_items_table',3);
INSERT INTO migrations VALUES(72,'2024_04_09_195024_add_soft_deletes_to_store_settings',4);
INSERT INTO migrations VALUES(73,'2021_10_16_171140_create_stackkit_cloud_tasks_table',5);
INSERT INTO migrations VALUES(74,'2024_04_25_154346_add_trial_expires_at_to_orders_table',6);
INSERT INTO migrations VALUES(75,'2024_05_08_154024_domain_unique_with_deleted_at_index',7);
INSERT INTO migrations VALUES(76,'2024_05_13_145233_add_current_period_start_to_billings_subscriptions_table',8);
INSERT INTO migrations VALUES(77,'2024_05_13_154241_add_authorization_expires_at_to_payment_transactions_table',9);
INSERT INTO migrations VALUES(78,'2024_05_13_154331_add_transaction_source_name_to_payment_transactions_table',9);
INSERT INTO migrations VALUES(79,'2024_05_53_174445_add_is_first_of_billing_cycle_to_billings_charges_table',10);
INSERT INTO migrations VALUES(80,'2024_05_17_074719_update_source_transaction_name_to_nullable_at_payments_transactions_table',11);
INSERT INTO migrations VALUES(81,'2024_05_20_140842_add_is_first_of_billing_period_to_billings_tbyb_net_sales_table',12);
INSERT INTO migrations VALUES(82,'2024_05_20_140842_add_is_first_of_billing_period_to_orders_tbyb_net_sales_table',12);
INSERT INTO migrations VALUES(83,'2024_05_21_002036_drop_auth_expires_at_and_source_transaction_name_of_payments_transactions_table',13);
INSERT INTO migrations VALUES(84,'2024_05_21_163613_add_time_ranges_to_billings_charges_table',14);
INSERT INTO migrations VALUES(85,'2024_05_28_153538_add_original_quantity_to_line_items_table',14);
INSERT INTO migrations VALUES(86,'2024_06_06_180134_add_refund_data_to_refunds_table',14);
INSERT INTO migrations VALUES(87,'2024_06_12_161514_add_order_name_to_orders_transactions',15);
